### ISSUE TITLE
UnboundLocalError: local variable 'url_' referenced before assignment 

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1]
This is a copy of a bug opened by Klaus Kaempf on pywbem@SF: https://sourceforge.net/p/pywbem/bugs/37/

**Symptom:**

Installation of tog-pegasus fails on openSUSE with:

Additional rpm output:
MOF import failed! Check /var/lib/Pegasus/loadmof.log for details.
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/pywbem/mof_compiler.py", line 1765, in <module>
mofcomp.compile_file(fname, options.ns)

...
File "/usr/lib64/python2.7/site-packages/pywbem/cim_http.py", line 482, in wbem_request
s = os.stat(url_)

The offending command is

/usr/sbin/pegutil /usr/lib64/python2.7/site-packages/pywbem/mof_compiler.py -n root/cimv2 -s /usr/share/mof/cim-current -u /var/run/tog-pegasus/cimxml.socket /usr/share/mof/cim-current/Interop/CIM_Namespace.mof

**Root cause:**

Looking at cim_http.py around line 482 reveals:

    if url.startswith('http'):
        h = HTTPConnection(host,
                           port=port,
                           timeout=timeout)
    else:
        if url.startswith('file:'):
            url_ = url[5:]
        try:
            s = os.stat(url_)

Looks like the "if url.startswith('file:'):" line is missing an "else:" statement ?

**Fix:**

This seems to fix the error

    --- /usr/lib64/python2.7/site-packages/pywbem/cim_http.py~ 2015-03-06 10:53:53.489107675 +0100
    +++ /usr/lib64/python2.7/site-packages/pywbem/cim_http.py 2015-03-06 10:54:27.773181173 +0100
    @@ -479,6 +479,8 @@
    else:
    if url.startswith('file:'):
    url_ = url[5:]
    + else:
    + url_ = url
    try:
    s = os.stat(url_)
    if S_ISSOCK(s.st_mode):

**Comment by andy-maier** [comment]
Fixed as proposed, in v0.8.0-rc1.

**Comment by andy-maier** [comment]
This fix has been released in v0.8.0-dev.20151008 (See [dist/pywbem-0.8.0](https://github.com/pywbem/pywbem/tree/master/dist/pywbem-0.8.0) directory).
