### ISSUE TITLE
Issues with mof_compiler python script compiling mof.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1157]
1. When in not verbose mode (-v)  mof_compiler script does not display errors such as bad parameters.

The following error (bad server name) only results in output of error message when the -v flag is set.

```

    (pywbem27) kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem(master)$ mof_compiler -s blah testsuite/test.mof
    (pywbem27) kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem(master)$ mof_compiler -v -s blah testsuite/test.mof
    MOF repository: Namespace root/cimv2 in WBEM server blah
    Compiling file ./testsuite/test.mof
    Creating class root/cimv2:PyWBEM_Person

```

In the above example, there is no server blah but that error is completely hidden even in verbose mode.  It implies that it is creating one class but obviously creates nothing.

NOTE: When correctly executed the following occurs:

```
  wbem27) kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem(master)$ mof_compiler -v -s http://localhost testsuite/test.mof
    MOF repository: Namespace root/cimv2 in WBEM server http://localhost
    Compiling file ./testsuite/test.mof
    Creating class root/cimv2:PyWBEM_Person
    Created class root/cimv2:PyWBEM_Person
    Creating class root/cimv2:PyWBEM_PersonCollection
    Created class root/cimv2:PyWBEM_PersonCollection
    Creating class root/cimv2:PyWBEM_MemberOfPersonCollection
    Created class root/cimv2:PyWBEM_MemberOfPersonCollection
    Creating instance of PyWBEM_Person.
    Creating instance of PyWBEM_Person.
    Creating instance of PyWBEM_Person.
    Creating instance of PyWBEM_PersonCollection.
    Creating instance of PyWBEM_MemberOfPersonCollection.
    Creating instance of PyWBEM_MemberOfPersonCollection.
    Creating instance of PyWBEM_MemberOfPersonCollection.
    Creating class root/cimv2:PyWBEM_AllTypes
    Created class root/cimv2:PyWBEM_AllTypes
    Creating instance of PyWBEM_AllTypes.
    Creating instance of PyWBEM_AllTypes.

```

2. Trying to do a dry run results in the following: This is because url is not an attribute in MOFWBEMConnection.

```
    (pywbem27) kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem(master)$ mof_compiler -v -d -s http://localhost testsuite/test.mof
    Traceback (most recent call last):
      File "/home/kschopmeyer/.virtualenvs/pywbem27/bin/mof_compiler", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/mof_compiler", line 293, in <module>
    rc = main()  # pylint: disable=invalid-name
      File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/mof_compiler", line 255, in main
    (conn.default_namespace, conn.url))
    AttributeError: 'MOFWBEMConnection' object has no attribute 'url'

```
Note that simply removing the -d options results in correct compilation as shown above so it is not an issue with the url presented as well does removing the -v parameter since the message at line 255 of mof_compiler is tied to verbose more.

**Comment by andy-maier** [comment]
Fixed in PR #1163.
