### ISSUE TITLE
FakedWBEMConnection cannot log

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1181]
The following sequence of python statements shows that FakedWBEMConnection cannot log:

```
>>> import pywbem
>>> import logging_tree as lt
>>> pywbem.configure_logger('api', connection=True)
>>> lt.printout()
<--""
   Level WARNING
   |
   o<--"BIO"
   |   Level NOTSET so inherits level WARNING
   |
   o<--"EVP"
   |   Level NOTSET so inherits level WARNING
   |
   o<--[M2Crypto]
   |   |
   |   o<--"M2Crypto.AuthCookie"
   |   |   Level NOTSET so inherits level WARNING
   |   |
   |   o<--[M2Crypto.SSL]
   |   |   |
   |   |   o<--"M2Crypto.SSL.Connection"
   |   |       Level NOTSET so inherits level WARNING
   |   |
   |   o<--"M2Crypto.X509"
   |       Level NOTSET so inherits level WARNING
   |
   o<--[pywbem]
   |   |
   |   o<--"pywbem.api"
   |       Level DEBUG
   |       Handler File '/media/share/Projects/pywbem/repos/pywbem/pywbem.log'
   |         Formatter fmt='%(asctime)s-%(name)s-%(message)s' datefmt=None
   |
   o<--"util"
       Level NOTSET so inherits level WARNING
>>> import pywbem_mock
>>> conn=pywbem_mock.FakedWBEMConnection()
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "pywbem_mock/_wbemconnection_mock.py", line 335, in __repr__
    (self.__class__.__name__, self.response_delay,
  File "pywbem_mock/_wbemconnection_mock.py", line 322, in response_delay
    return self._response_delay
AttributeError: 'FakedWBEMConnection' object has no attribute '_response_delay'
Logged from file _recorder.py, line 606
>>>
```

Initial analysis shows that the reason for this is a circular dependency: The log record for the connection is created in the WBEMConnection ctor, where the attributes added by the derived class FakedWBEMConnection, i.e. _response_delay, are not yet set on the object.

**Comment by andy-maier** [comment]
**Discussion point:** Part of 0.12 or not?

**Comment by KSchopmeyer** [comment]
Actually it logs if the connection is setup before the config but not if it is setup after.  At least that appears to be the case.  See example test_5 in test_recorder.py.

But that does not mitigate the issue.

**Comment by KSchopmeyer** [comment]
I Tried the following,

```

        """
        # Response delay in seconds. Any operation is delayed by this time.
        self._response_delay = response_delay

        super(FakedWBEMConnection, self).__init__(
            'http://FakedUrl',
            default_namespace=default_namespace,
            use_pull_operations=use_pull_operations,
            stats_enabled=stats_enabled)

```
which initializes the _response_delay before the superclass __init__ is called and that clears the issue. Once I had code to fix the issue in #1184 I was getting caught in the attrib error all the time so I tried that change.

Not sure what the python rules for this are however.

**Comment by KSchopmeyer** [comment]
Andy correct but should probably have left open until pr #1185 was committed.   I assume that Andh's comment means he agrees with my change to  move of _response_delay
