### ISSUE TITLE
FakedWBEMConnection cannot add CIMInstance that has path without keybindings

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1182]
If one attempts to use add_cimobjects() to add a CIMInstance object that has a path without keybindings, this results in a ValueError exception stating the instance has no path.

First, the exception message is misleading because the instance in fact does have a path.
Second, this ought to work.

```
>>> import pywbem
>>> import pywbem_mock
>>> i1=pywbem.CIMInstance('C1',path=pywbem.CIMInstanceName('C1'))
>>> conn=pywbem_mock.FakedWBEMConnection()
>>> conn.add_cimobjects(i1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywbem_mock/_wbemconnection_mock.py", line 551, in add_cimobjects
    if not inst.path:
ValueError: Instances added must include path. Inst CIMInstance(classname=u'C1', path=CIMInstanceName(classname=u'C1', keybindings=NocaseDict([]), namespace=None, host=None), ...) does not include a path
```

Initial analysis shows that this is caused by a combination of (1) using `if not inst.path:` (on line 550 in _wbemconnection_mock.py) for testing whether the instance has a path, and (2) a behavior of a CIMInstancePath object with no keybindings that is caused by the fact that we want to allow using such an object like a dictionary of its keys, and that can be described as unexpected (at least to me):

```
>>> ip1=pywbem.CIMInstanceName(classname=u'C1')  # no keybindings
>>> len(ip1)
0  # expected
>>> not ip1
True  # not expected
>>> bool(ip1)
False  # not expected
```

Debugging this reveals that at least "not" invokes len(), which explains the result.

It seems the consequence is that for all CIM objects that behave like dictionaries (CIMInstance and CIMInstanceName), it is dangerous to use "not" on them, like when testing whether a CIMInstance has a path. This should be replaced with testing for None.

**Comment by andy-maier** [comment]
Fixed by PR #1183.
