### ISSUE TITLE
install_dmtf_schema fails with python3

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#1218]
Traceback (most recent call last):
  File "testsuite/test_mof_compiler.py", line 43, in setUpModule
    install_dmtf_schema()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/dmtf_mof_schema_def.py", line 105, in install_dmtf_schema
    fp.write(data)
TypeError: must be str, not bytes

This works with python 2 which is why we never found it before.  

**NOTE:** My intention is to replace this with the pr from issue #1187 so is is probably not worthwhile actually fixing this issue, just deciding what the fix is since the same code to install a schema is in #1187 

The fix is to write the zip file from the dmtf as w+b I believe

**Comment by andy-maier** [comment]
This issue is also solved by PR #1220.
