### ISSUE TITLE
Pytest cannot load its plugin 'pytest_cov' with latest package level

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1371]
`make test` fails because pytest cannot load its plugin 'pytest_cov'.

The following traceback is from Travis run: https://travis-ci.org/pywbem/pywbem/jobs/424857470

```
bash -c "set -o pipefail; PYTHONWARNINGS=default py.test --color=yes --cov pywbem --cov pywbem_mock  --cov-config coveragerc  --ignore=attic --ignore=releases -s 2>&1 |tee test_27.tmp.log"
/opt/python/2.7.14/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sphinxcontrib': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 56, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 181, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 617, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 782, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config/__init__.py", line 734, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/manager.py", line 259, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e))
pluggy.manager.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (coverage 4.0.3 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('coverage>=4.4'))!
make: *** [test] Error 1
```

**Comment by andy-maier** [comment]
Analysis shows that this is related to the issue around requiring different versions of the `coverage` package:

`pytest-cov` 2.6.0 has increased the version requirement for the `coverage` package from >=3.7.1 to >=4.4, which is in conflict with the version requirement defined by the `python-coveralls` package for coverage==4.0.3.

Issue https://github.com/z4r/python-coveralls/issues/66 has been opened.

Workaround is to pin the `pytest_cov` version to below 2.6.0.

**Comment by andy-maier** [comment]
PR #1370 implements the workaround to pin the pytest_cov version to below 2.6.0.

**Comment by jkMugabe** [comment]
python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.2 which is incompatible

**Comment by jkMugabe** [comment]
i need the solution please
