### ISSUE TITLE
pywbem parse error on dodgy datetime instance property

### ISSUE THREAD

**Issue by dugganj** [pywbem/pywbem#1379]
The attached code throws a pywbem.exceptions.ParseError.  The datetime argument ("20180911124613.128***:000") is admittedly an improperly formatted datetime value.

The thing is *I don't care* about the value of this parameter.  I really, really need to get the other properties (such as job status / job completion, etc.).  So pywbem throwing an exception, and leaving me no recourse to get the other properties, caused me to use a competing Webm Service implementation to get the data I needed.

**Comment by dugganj** [comment]
import pywbem as pw

URL='https://10.1.134.96'
PRINCIPAL='smilab'
PASSWORD='F00sb4ll'

conn = pw.WBEMConnection(URL, (PRINCIPAL, PASSWORD))
scsInstName = pw.CIMInstanceName(classname='CMPL_StorageConfigurationService',
                                 keybindings=[('CreationClassName', 'CMPL_StorageConfigurationService'),
                                              ('Name', '60964:CMPL_SCS'),
                                              ('SystemCreationClassName', 'CMPL_ComputerSystem'),
                                              ('SystemName', '10.1.134.170')],
                                 namespace='root/compellent',
                                 host='10.1.134.96')
poolInstName = pw.CIMInstanceName(classname='CMPL_StorageConfigurationService',
                              keybindings=[('CreationClassName', 'CMPL_StorageConfigurationService'),
                                           ('Name', '60964:CMPL_SCS'),
                                           ('SystemCreationClassName', 'CMPL_ComputerSystem'),
                                           ('SystemName', '10.1.134.170')],
                              namespace='root/compellent',
                              host='10.1.134.96')
parms = []
parms.append(pw.CIMParameter("ElementName", "string", value="StorageVolume"))
parms.append(pw.CIMParameter("Size", "uint64", value=1000000))
parms.append(pw.CIMParameter("InPool", "reference", reference_class="CIM_StoragePool", value=poolInstName))
retVal = conn.InvokeMethod("CreateOrModifyElementFromStoragePool", scsInstName, Params=parms)
jobInst = conn.GetInstance(retVal[1]['Job'])

**Comment by dugganj** [comment]
This was run against the Dell Compllent at the SMI Lab in the SNIA tech center.

**Comment by dugganj** [comment]
Stack trace...

Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 2048, in unpack_string
    value = CIMDateTime(data)
  File "C:\Miniconda3\lib\site-packages\pywbem\cim_types.py", line 370, in __init__
    'datetime format' % dtarg)
ValueError: dtarg argument "20180911124613.128***:000" has an invalid CIM datetime format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/dugganj/PycharmProjects/untitled/DellDateTimeBug.py", line 27, in <module>
    jobInst = conn.GetInstance(retVal[1]['Job'])
  File "C:\Miniconda3\lib\site-packages\pywbem\cim_operations.py", line 2482, in GetInstance
    **extra)
  File "C:\Miniconda3\lib\site-packages\pywbem\cim_operations.py", line 1628, in _imethodcall
    tup_tree = parse_cim(tt_)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 336, in parse_cim
    child = one_child(tup_tree, ['MESSAGE', 'DECLARATION'])
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 229, in one_child
    return parse_any(child)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1919, in parse_any
    return funct_name(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1522, in parse_message
    'MULTIEXPRSP'])
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 229, in one_child
    return parse_any(child)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1919, in parse_any
    return funct_name(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1758, in parse_simplersp
    child = one_child(tup_tree, ['METHODRESPONSE', 'IMETHODRESPONSE'])
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 229, in one_child
    return parse_any(child)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1919, in parse_any
    return funct_name(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1811, in parse_imethodresponse
    'PARAMVALUE'])
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 261, in list_of_various
    result.append(parse_any(child))
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1919, in parse_any
    return funct_name(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1891, in parse_ireturnvalue
    'VALUE.INSTANCEWITHPATH'])
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 304, in list_of_same
    result.append(parse_any(child))
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1919, in parse_any
    return funct_name(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1050, in parse_instance
    'PROPERTY.ARRAY'])
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 276, in list_of_matching
    result.append(parse_any(child))
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1919, in parse_any
    return funct_name(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 1231, in parse_property
    val = unpack_value(tup_tree)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 2007, in unpack_value
    return unpack_single_value(raw_val, valtype)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 2023, in unpack_single_value
    return unpack_string(data, cimtype)
  File "C:\Miniconda3\lib\site-packages\pywbem\tupleparse.py", line 2050, in unpack_string
    raise ParseError("Invalid datetime value: %r (%s)" % (data, exc))
pywbem.exceptions.ParseError: Invalid datetime value: '20180911124613.128***:000' (dtarg argument "20180911124613.128***:000" has an invalid CIM datetime format)

**Comment by andy-maier** [comment]
We'll fix that. Likely tomorrow.

**Comment by andy-maier** [comment]
@dugganj Just for the record: The string "20180911124613.128***:000" is in fact a valid CIM datetime value according to DSP0004 (see 5.2.4 "Datetime Type"). pywbem simply did not support asterisks in the input string for `pywbem.CIMDateTime`, so far.

**Comment by andy-maier** [comment]
PR #1381 fixes this for the upcoming pywbem version 0.13.0.
We will roll this back into 0.12.x.

**Comment by dugganj** [comment]
Yay!  I found a bona fide bug!

**Comment by andy-maier** [comment]
:-) !!
Glad you found it. We missed that one completely!
