### ISSUE TITLE
PyInstaller: Project name pywbem was given, but was not able to be found.

### ISSUE THREAD

**Issue by karo33wang** [pywbem/pywbem#1410]
**ENV**
OS: Ubuntu16.04
pip version: pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
pywbem version: pywbem-0.12.6

**Error**
I build an elf which using pywbem on one Ubuntu16.04_1, then upload this elf to another Ubuntu16.04_2 with same ENV. On 1, this elf runs well, but on 2, it reports error:
```

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pywbem/__init__.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pywbem/_listener.py", line 141, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pywbem/_version.py", line 46, in <module>
  File "pbr/version.py", line 457, in release_string
  File "pbr/version.py", line 462, in semantic_version
  File "pbr/version.py", line 449, in _get_version_from_pkg_resources
  File "pbr/packaging.py", line 812, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pywbem was given, but was not able to be found.
[19695] Failed to execute script name.py
```

I see pywbem is under /usr/local/lib/python2.7/dist-packages already.
What's wrong and how to fix it?

Thanks in advance!

**Comment by andy-maier** [comment]
The pbr package used by pywbem for automatic package version determination needs the PKG-INFO file. I assume the error you see is caused by that file not being present. We added that file recently to the git repo, so that for example the tarball that is built by github can be installed properly. Can you try including that file and see if it solves the issue?

PS: What is an "elf" and how do you build it?

**Comment by karo33wang** [comment]
I reinstall it with pywbem-0.12.6.tar.gz (I want to use the same version on my Ubuntus). PKG-INFO is in it already, but still fail with the same error. I find pbr version on my good Ubuntu is pbr-4.0.1, but the failed Ubuntu is pbr-4.3.0. I used "pip install pywbem==0.12.6" to install pywbem on both machines at the first time, not sure why pbr version is different. Any more suggestion?

elf means an executable file. I build it with command "pyinstaller -F *.py".

**Comment by karo33wang** [comment]
I tried "pip install --upgrade distribute", still failed.
Also I reinstall pbr version 4.0.1, fail again.

**Comment by karo33wang** [comment]
It works after I copy the PKG_INFO file into the directory which is running the executable file. But still don't know why on Ubuntu16.04_1, this step needn't to do.

**Comment by andy-maier** [comment]
I have started looking into this and made my first attempts to use pyinstaller. This is a strange piece of software: The xref file it produces reports packages as missing that are definitely present and that the generated file can find. Its `--debug all` option does not seem to display anything in addition.

Also, in the one-file mode, the generated executable represents only one single command. You should not invoke it with "*.py", but with exactly only the python script file you want it to invoke.

When you generate the executable:
- does your current Python environment have the pywbem package installed, i.e. is it listed with `pip list`?
- are you running the pyinstaller command in the work directory of a checked out pywbem repository?

**Comment by karo33wang** [comment]
Yes, I specified the name of .py to build executable file.

Pywbem has been installed on both machines. If it's not installed, python will report can't find Pywbem error.
**On Ubuntu1:**
```
# pip list
pywbem (0.12.6)
```
**On Ubuntu2:**
```
# pip list
pywbem (0.12.1.dev94)   ---> I tried to clone code from github directly after the failure of 0.12.6
```
I only do pyinstaller on ubuntu1, and upload the executable file to ubuntu2. Because I can only let customer machine run the executable file instead of getting the source code due to security.

**Comment by andy-maier** [comment]
You need the Python environment with installed packages only for running the pyinstaller command, which is generating the executable. For running the generated executable, no Python environment is needed at all, because all of that is now in the executable. I don't know whether the executable ignores that Python environment or maybe gets confused by it. It is worth a try in any case to run the executable in a Python environment that does not have pywbem installed.

**Comment by karo33wang** [comment]
Sorry, I forgot to say that I saw this error first, then tried to install pywbem on ubuntu2 directly. Now I try one other ubuntu, still see this error if without PKG-INFO.

**Comment by andy-maier** [comment]
I suspect that PyInstaller does not include the package metadata into the generated executable. When you run the generated executable on your original Ubuntu, the metadata was probably still available somehow (e.g. because you still had the virtual Python environment active), but on your second Ubuntu, it was not. That is why the PKG-INFO file helped: that is a fallback option for pbr when it cannot determine the package metadata.

In order to get clarification on that, I have opened issue https://github.com/pyinstaller/pyinstaller/issues/3805.

If it turns out that PyInstaller actually does not include the package metadata into the generated executable, then a good solution will be difficult ... but let's wait and see.

**Comment by andy-maier** [comment]
@karo33wang Could you please try out the answer with the PyInstaller hook for pbr that was proposed in a comment on issue pyinstaller/pyinstaller#3805 ?

**Comment by karo33wang** [comment]
Still see the same error with hook. But not sure if my procedure is right.
1. \# vi hook-pbr.py
```
from PyInstaller.utils.hooks import copy_metadata
copy_metadata('pbr')
```
2. \# pyinstaller -F name.py --additional-hooks-dir .
```
...
97034 INFO: Loading module hook "hook-httplib.py"...
97038 INFO: Loading module hook "hook-pbr.py"...
97052 INFO: Loading module hook "hook-pydoc.py"...
...
```
3. scp the new executable to ubuntu2 and run
```
File "pywbem/_version.py", line 46, in <module>
  File "pbr/version.py", line 457, in release_string
  File "pbr/version.py", line 462, in semantic_version
  File "pbr/version.py", line 449, in _get_version_from_pkg_resources
  File "pbr/packaging.py", line 812, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pywbem was given, but was not able to be found.
[10069] Failed to execute script name
```

**Comment by karo33wang** [comment]
Still see this error with hook, but not sure if my procedure is right.
1. vi hook-pbr.py
```
from PyInstaller.utils.hooks import copy_metadata

copy_metadata('pbr')
```
2. pyinstaller -F name.py --additional-hooks-dir .
```
...
97034 INFO: Loading module hook "hook-httplib.py"...
97038 INFO: Loading module hook "hook-pbr.py"...
97052 INFO: Loading module hook "hook-pydoc.py"...
...
```
3. scp the new executable to ubuntu2 and run
```
 File "pywbem/_version.py", line 46, in <module>
  File "pbr/version.py", line 457, in release_string
  File "pbr/version.py", line 462, in semantic_version
  File "pbr/version.py", line 449, in _get_version_from_pkg_resources
  File "pbr/packaging.py", line 812, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pywbem was given, but was not able to be found.
[10069] Failed to execute script name
```

**Comment by andy-maier** [comment]
First, sorry for the long delay. I don't really know what to do at this point, except trying to start using PyInstaller, which does not seem to be a easy start. Karl and I will see if we can give it a try, but probably after releasing pywbem 0.13.

What are you using this for, is this your private way of setting up your system, or are you packaging that up for some release package?

**Comment by andy-maier** [comment]
We have put PyInstaller support on the list for pywbem 0.14.0.

**Comment by andy-maier** [comment]
PR #1876 removes the use of pbr in the master branch, and #1877 in the fix branch (we still need to decide whether that PR goes into 0.14.6 or into a new 0.15.0).

I verified that I was able to create a onefile version of a copy of wbemcli (as mywbemcli.py) with pyinstaller 3.5 and Python 3.7 on on macos.

Example, using the branch of PR #1876 
```
$ cp wbemcli mywbemcli.py
$ pyinstaller --onefile mywbemcli.py
$ dist/mywbemcli --version
mywbemcli 1.0.0.dev1
```

**Comment by andy-maier** [comment]
Closing this issue due to inactivity. Please feel free to reopen it, if needed.
