### ISSUE TITLE
Handling query result - format issues

### ISSUE THREAD

**Issue by PepperMan1** [pywbem/pywbem#1681]
Hi!
I'm using 
 - opensuse leap 15.0
 - python 3.6.5
 - pywbem 0.13.0
 - sfcbd 1.4.9
 - sblim-cmpi-base 1.6.4-lp150.28.1

Many queries on localhost are working fine but when I'm trying to query for example 'SELECT *  FROM Linux_UnixProcess' using  'ExecQuery' and printing result I'm getting error 
"AttributeError: 'MinutesFromUTC' object has no attribute '__offset'"
(using IterEnumerateInstances same error).

I'm doing something wrong or it's some pywbem bug? 

> Traceback (most recent call last):
  File "main.py", line 65, in <module>
    print(res)
  File "/usr/lib/python3.6/site-packages/pywbem/cim_obj.py", line 2611, in __repr__
    s=self)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 269, in _format
    return _ASCII2_FORMATTER.format(format_str, *args, **kwargs)
  File "/usr/lib64/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib64/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib64/python3.6/string.py", line 238, in _vformat
    obj = self.convert_field(obj, conversion)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 255, in convert_field
    return _ascii2(value)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 226, in _ascii2
    ret = ascii(value)  # returns type str in py2 and py3
  File "/usr/lib/python3.6/site-packages/pywbem/_nocasedict.py", line 373, in __repr__
    for key, value in self.iteritems()]
  File "/usr/lib/python3.6/site-packages/pywbem/_nocasedict.py", line 373, in <listcomp>
    for key, value in self.iteritems()]
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 269, in _format
    return _ASCII2_FORMATTER.format(format_str, *args, **kwargs)
  File "/usr/lib64/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib64/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib64/python3.6/string.py", line 238, in _vformat
    obj = self.convert_field(obj, conversion)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 255, in convert_field
    return _ascii2(value)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 226, in _ascii2
    ret = ascii(value)  # returns type str in py2 and py3
  File "/usr/lib/python3.6/site-packages/pywbem/cim_obj.py", line 4848, in __repr__
    s=self)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 269, in _format
    return _ASCII2_FORMATTER.format(format_str, *args, **kwargs)
  File "/usr/lib64/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib64/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib64/python3.6/string.py", line 238, in _vformat
    obj = self.convert_field(obj, conversion)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 255, in convert_field
    return _ascii2(value)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 226, in _ascii2
    ret = ascii(value)  # returns type str in py2 and py3
  File "/usr/lib/python3.6/site-packages/pywbem/cim_types.py", line 704, in __repr__
    s=self)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 269, in _format
    return _ASCII2_FORMATTER.format(format_str, *args, **kwargs)
  File "/usr/lib64/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib64/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib64/python3.6/string.py", line 238, in _vformat
    obj = self.convert_field(obj, conversion)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 255, in convert_field
    return _ascii2(value)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 226, in _ascii2
    ret = ascii(value)  # returns type str in py2 and py3
  File "/usr/lib/python3.6/site-packages/pywbem/cim_types.py", line 254, in __repr__
    s=self)
  File "/usr/lib/python3.6/site-packages/pywbem/_utils.py", line 269, in _format
    return _ASCII2_FORMATTER.format(format_str, *args, **kwargs)
  File "/usr/lib64/python3.6/string.py", line 190, in format
    return self.vformat(format_string, args, kwargs)
  File "/usr/lib64/python3.6/string.py", line 194, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib64/python3.6/string.py", line 234, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib64/python3.6/string.py", line 305, in get_field
    obj = getattr(obj, i)
AttributeError: 'MinutesFromUTC' object has no attribute '__offset'

**Comment by andy-maier** [comment]
Hi. An AttributeError is always a pywbem bug. Can you please provide the CIM-XML of the response (eg via the conn.last_raw_reply attribute)?

**Comment by PepperMan1** [comment]
Attached result is from `SELECT * FROM Linux_TimeService` - same error but much shorter result.

`<?xml version="1.0" encoding="utf-8" ?>
<CIM CIMVERSION="2.0" DTDVERSION="2.0">
<MESSAGE ID="1001" PROTOCOLVERSION="1.0">
	<SIMPLERSP>
		<IMETHODRESPONSE NAME="ExecQuery">
			<IRETURNVALUE>
				<VALUE.OBJECTWITHPATH>
					<INSTANCEPATH>
						<NAMESPACEPATH>
							<HOST>linux-s4vf</HOST>
							<LOCALNAMESPACEPATH>
								<NAMESPACE NAME="root"/>
								<NAMESPACE NAME="cimv2"/>
							</LOCALNAMESPACEPATH>
						</NAMESPACEPATH>
						<INSTANCENAME CLASSNAME="Linux_SystemTimeService">
							<KEYBINDING NAME="SystemCreationClassName">
								<KEYVALUE VALUETYPE="string">Linux_ComputerSystem</KEYVALUE>
							</KEYBINDING>
							<KEYBINDING NAME="SystemName">
								<KEYVALUE VALUETYPE="string">linux-s4vf</KEYVALUE>
							</KEYBINDING>
							<KEYBINDING NAME="CreationClassName">
								<KEYVALUE VALUETYPE="string">Linux_SystemTimeService</KEYVALUE>
							</KEYBINDING>
							<KEYBINDING NAME="Name">
								<KEYVALUE VALUETYPE="string">cmpiutil:timeservice</KEYVALUE>
							</KEYBINDING>
						</INSTANCENAME>
					</INSTANCEPATH>
					<INSTANCE CLASSNAME="Linux_SystemTimeService">
						<PROPERTY NAME="Generation" TYPE="uint64"></PROPERTY>
						<PROPERTY NAME="ElementName" TYPE="string"></PROPERTY>
						<PROPERTY NAME="Description" TYPE="string"></PROPERTY>
						<PROPERTY NAME="Caption" TYPE="string"></PROPERTY>
						<PROPERTY NAME="InstanceID" TYPE="string"></PROPERTY>
						<PROPERTY NAME="PrimaryStatus" TYPE="uint16"></PROPERTY>
						<PROPERTY NAME="OperatingStatus" TYPE="uint16"></PROPERTY>
						<PROPERTY NAME="DetailedStatus" TYPE="uint16"></PROPERTY>
						<PROPERTY NAME="CommunicationStatus" TYPE="uint16"></PROPERTY>
						<PROPERTY NAME="HealthState" TYPE="uint16">
							<VALUE>5</VALUE>
						</PROPERTY>
						<PROPERTY NAME="Status" TYPE="string">
							<VALUE>OK</VALUE>
						</PROPERTY>
						<PROPERTY.ARRAY NAME="StatusDescriptions" TYPE="string"></PROPERTY.ARRAY>
						<PROPERTY.ARRAY NAME="OperationalStatus" TYPE="uint16">
							<VALUE.ARRAY>
								<VALUE>2</VALUE>
							</VALUE.ARRAY>
						</PROPERTY.ARRAY>
						<PROPERTY NAME="InstallDate" TYPE="datetime">
							<VALUE>20190313114009.428200-240</VALUE>
						</PROPERTY>
						<PROPERTY NAME="TransitioningToState" TYPE="uint16">
							<VALUE>12</VALUE>
						</PROPERTY>
						<PROPERTY.ARRAY NAME="AvailableRequestedStates" TYPE="uint16"></PROPERTY.ARRAY>
						<PROPERTY NAME="TimeOfLastStateChange" TYPE="datetime">
							<VALUE>20190313114009.428174-240</VALUE>
						</PROPERTY>
						<PROPERTY NAME="EnabledDefault" TYPE="uint16">
							<VALUE>2</VALUE>
						</PROPERTY>
						<PROPERTY NAME="RequestedState" TYPE="uint16">
							<VALUE>12</VALUE>
						</PROPERTY>
						<PROPERTY NAME="OtherEnabledState" TYPE="string"></PROPERTY>
						<PROPERTY NAME="EnabledState" TYPE="uint16">
							<VALUE>2</VALUE>
						</PROPERTY>
						<PROPERTY NAME="LoSOrgID" TYPE="string"></PROPERTY>
						<PROPERTY NAME="LoSID" TYPE="string"></PROPERTY>
						<PROPERTY NAME="Started" TYPE="boolean">
							<VALUE>TRUE</VALUE>
						</PROPERTY>
						<PROPERTY NAME="StartMode" TYPE="string">
							<VALUE>Automatic</VALUE>
						</PROPERTY>
						<PROPERTY NAME="PrimaryOwnerContact" TYPE="string"></PROPERTY>
						<PROPERTY NAME="PrimaryOwnerName" TYPE="string"></PROPERTY>
						<PROPERTY NAME="Name" TYPE="string">
							<VALUE>cmpiutil:timeservice</VALUE>
						</PROPERTY>
						<PROPERTY NAME="CreationClassName" TYPE="string">
							<VALUE>Linux_SystemTimeService</VALUE>
						</PROPERTY>
						<PROPERTY NAME="SystemName" TYPE="string">
							<VALUE>linux-s4vf</VALUE>
						</PROPERTY>
						<PROPERTY NAME="SystemCreationClassName" TYPE="string">
							<VALUE>Linux_ComputerSystem</VALUE>
						</PROPERTY>
					</INSTANCE>
				</VALUE.OBJECTWITHPATH>
			</IRETURNVALUE>
		</IMETHODRESPONSE>
	</SIMPLERSP>
</MESSAGE>
</CIM>`

**Comment by PepperMan1** [comment]
In case of `python -c "import pywbem; d=pywbem.CIMDateTime('20190313114009.428200-240'); print(repr(d))"` running with `python` don't throw error but `python3`  yes

**Comment by andy-maier** [comment]
Apparently that depends. On my MacOs with python 2.7.15, it does throw the error.

The error is that the __repr__() methof of the CIMDateTime class uses a format string with a double underscored attribute, which is apparently not supported in all Python versions. The double underscore causes name mangling with the class name to happen, but the interpretation of the attribute in the format string apparently does not apply that name mangling.

Plus, pywbem so far does not have unit testcases for repr(CIMDateTime), so the error went by undetected.

**Comment by andy-maier** [comment]
I have fixed the error and have added testcases for repr() and str(). That will be released shortly as version 0.13.1.

**Comment by andy-maier** [comment]
pywbem 0.13.1 which includes the fix for this issue has been released to Pypi.
