### ISSUE TITLE
Sometimes, couldn't get instances from Associators

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#1775]
Hello everybody:

Sometimes, I try to get instances by Associators function, but it return an empty list. Actually, the instances exist and the numble of instances is 10. The issue can’t reproduce every time. It only happen when my cim client have connection exception with cim agent.

I write a test code that run 10000 loop for reproducing the issue.

```
for i in range(0, 10000):
    insts = conn.Associators(cluster_paths[0], ResultClass="IBMTSSVC_SynchronizedSet")
    if len(insts) != 10:
        print("Issue happen =========")
        print(len(insts))

Issue happen =========
0
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/root/pywbem/pywbem/cim_operations.py", line 3371, in Associators
    **extra)
  File "/root/pywbem/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/root/pywbem/pywbem/cim_http.py", line 858, in wbem_request
    raise AuthError(response.reason, conn_id=conn_id)
pywbem.exceptions.AuthError: Unauthorized
```

Whether or not can the Associators return an exception other than an empty list if it can’t get all expected instances? I try IterAssociatorInstances, it have same issue.

Also, why is the exception AuthError other than ConnectionError or TimeoutError? I use same WBEMConnection variable run the test. The authorization info should not be incorrectly. Actually, I wait 3-4 minuates, the WBEMConnection will be valid again.

Thanks you very much.
Ray

**Comment by andy-maier** [comment]
I'm not sure I can see what happens since you were not posting all of your code, so I can only speculate: One of the calls to Associators succeeds (in the sense that it does not raise an exception), but returns 0 instances. In the next turn of the loop, the next Associators call raises an AuthError, which is reported as a traceback.

I can only conclude that the WBEM server has thrown you out because you tried so many times. After some time, it re-enables itself again. Another option is that the server crashes and restarts after a while.

I'm not sure that the pywbem team can help you there.

**Comment by andy-maier** [comment]
Sorry for the delay. So that proves that there are many cases where it works, and then at some point the operation fails.

On the question why an AuthError is raised: pywbem looks at the CIM-XML response, and if that response indicates an auth error, it raises the pywbem.AuthError exception. The trigger for that is an HTTP status 401 (Not authorized). There is some logic in case of WBEM servers specified as file: URLs that are sockets, but I assume in your case we are talking about a normal HTTP or HTTPS connection over the network, and in that case, the logic in pywbem is straight forward: HTTP status 401 -> raise AuthError.

I found the following comment in pywbem.cim_http.py line 792 from the original authors:
```
               # An http server is allowed to send back an error (presumably
                # a 401), and close the connection without reading the entire
                # request.  A server may do this to protect itself from a DoS
                # attack.
```

So one possibility is that the server responded to the operation about 16000 times and then decided that this is an attack and denied further operations.

Another possibility is that the server crashes every now and then.

In both cases, there must be some evidence about what happens in the logs on the server side.

A pragmatic approach for pywbem would be to add retries in case of errors such as connection related errors or authentication related errors. There is already some retry logic, but it is pretty convoluted (and in your case tit does not retry). We would have to add a hold-off time before the next retry is performed. The problem with that is that it likely breaks the logic for the local (file: URL based) access to servers, particularly since one of them (OpenWBEM) is no longer an active project, but who knows which products have an old version of it running. This change would be something for the upcoming 1.0.0 version of pywbem.

**Comment by tanshaolong** [comment]
Thanks @andy-maier  for your detail reply.
Actualy, I have a retry code at my application for the AuthError and it works. But the retry just resolve the AuthError exception, it can’t resolve the issue of empty result without expection yet.

I am trying to use other method to avoid the issue. If you have some other better suggestions, please tell me. Thanks you again.

**Comment by andy-maier** [comment]
Oh, I forgot the behavior with the empty result. Sorry for that.

Can you please try to capture the CIM-XML response payload for such a case (i.e. check if result is empty, and then dump `conn.last_raw_reply`). I'd like to see if there is something in that response that should cause pywbem to raise an error instead of producing an empty result set.

**Comment by tanshaolong** [comment]
Sorry, I can't use the IBM V7000 device for some reasons currently. I will update the dump result if I get new device to test.

**Comment by andy-maier** [comment]
I am closing this issue due to inactivity. Please feel free to reopen it if needed, or to open a new issue.
