### ISSUE TITLE
EnumerateInstanceNames error 

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1776]
@andy-maier 
 env:
pywbem : 0.14.1.dev17
python : 3.5.7
system :  CentOS release 6.5 (Final)

hi ,I'd like to look at HuaSy_DiskDrive and how it works using EnumerateInstanceNames and how it works using filters. In addition, I can get results by looking at other information. Looking forward to your reply。

code 
>>> conn = pywbem.WBEMConnection('https://192.168.8.8', ('smis_admin', 'Admin@12'), 'root/huawei',None,None,None,True)
>>> data = self.conn.EnumerateInstances('HuaSy_DiskDrive')

error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pywbem/cim_http.py", line 826, in wbem_request
    response = client.getresponse()
  File "/usr/local/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/local/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/pywbem/cim_operations.py", line 2467, in EnumerateInstances
    **extra)
  File "/usr/local/lib/python3.5/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/lib/python3.5/site-packages/pywbem/cim_http.py", line 974, in wbem_request
    conn_id=conn_id)
pywbem.exceptions.ConnectionError: The server closed the connection without returning any response

**Comment by andy-maier** [comment]
This means essentially the server refused your attempt to talk with it.
Have you ever been able to get anything done with that server?

**Comment by KSchopmeyer** [comment]
Can I suggest that you try some of the other operations, ex. GetClass or EnumerateClass.  However, whatever the reason, the server is closing very early in the request  operation processing and returning nothing which gives us very little to work with.

**Comment by andy-maier** [comment]
Closed due to inactivity. Feel free to reopen.
