### ISSUE TITLE
Problem during make build with docutils 0.15

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1788]
Since today, `make build` fails as follows:
```
python setup.py sdist -d dist bdist_wheel -d dist --universal
running sdist
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.1s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.2s)
running egg_info
writing requirements to pywbem.egg-info/requires.txt
writing pywbem.egg-info/PKG-INFO
writing top-level names to pywbem.egg-info/top_level.txt
writing dependency_links to pywbem.egg-info/dependency_links.txt
writing pbr to pywbem.egg-info/pbr.json
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
writing manifest file 'pywbem.egg-info/SOURCES.txt'
[pbr] reno was not found or is too old. Skipping release notes
running check
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    pbr=True)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pbr/packaging.py", line 619, in run
    sdist.sdist.run(self)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/setuptools/command/sdist.py", line 52, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 845, in get_command_obj
    klass = self.get_command_class(command)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/setuptools/dist.py", line 838, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/readme_renderer/integration/distutils.py", line 21, in <module>
    from distutils.command.check import check as _check
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/check.py", line 13, in <module>
    from docutils.utils import Reporter
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/docutils/utils/__init__.py", line 21, in <module>
    import docutils.io
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/docutils/io.py", line 348
    (self.destination.mode, mode)), file=self._stderr)
                                        ^
SyntaxError: invalid syntax
```

Installing different versions of docutils reveals that docutils 0.15 introduced the issue.

**Comment by andy-maier** [comment]
The problem had already been reported in the docutils bug tracker as https://sourceforge.net/p/docutils/bugs/365/. I added the symptom we saw, because it was the same kind of error, but on a different source line of docutils.

I will pin docutils to 0.14 until the issue is fixed.

**Comment by andy-maier** [comment]
The following PRs have a workaround by pinning docutils to 0.14:
* PR #1789 for master (1.0.0)
* PR #1790 for 0.14.5.

**Comment by andy-maier** [comment]
The docutils project updated their 0.15 version with a fixed version. I did not know that this even is possible. PRs #1797 and #1796 unpin the docutils version, which is the final fix for this issue.
