### ISSUE TITLE
ssl  connect 

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1919]
hi andy-maier
env 
    Python 3.5.7 (default, Aug 16 2019, 10:17:32) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
   pywbem.__version__   '0.14.0'

error
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 2467, in EnumerateInstances
    **extra)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 813, in wbem_request
    client.endheaders()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/python3/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 480, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 646, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/local/python3/lib/python3.5/ssl.py", line 1027, in connect
    self._real_connect(addr, False)
  File "/usr/local/python3/lib/python3.5/ssl.py", line 1018, in _real_connect
    self.do_handshake()
  File "/usr/local/python3/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/python3/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()

Some devices have this problem
@andy-maier

**Comment by andy-maier** [comment]
What is the exception that is raised?

**Comment by andy-maier** [comment]
@allen0817 If you tell us which exception was raised, we could transform it to `pywbem.ConnectionError` to provide a more consistent experience at the API. If you do that within the next week or so, we could do that in the upcoming 0.15.0 version.

Also, without knowing the exception and its message, it is difficult to give you any advice on your actual problem.

**Comment by andy-maier** [comment]
This was described in issue #1950. Closing this issue.
