### ISSUE TITLE
AttributeError getsitepackages on Appveyor with Python 2.7 32-bit

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#1946]
On Appveyor with native Windows on Python 2.7 32-bit, we get the following issue since a few days, during `make check`:

```
[376] C:\projects\pywbem$ 'C:\ProgramData\chocolatey\bin\make.EXE' check
Traceback (most recent call last):
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 703, in <module>
    main()
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: 'module' object has no attribute 'getsitepackages'
Traceback (most recent call last):
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 703, in <module>
    main()
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: 'module' object has no attribute 'getsitepackages'
Traceback (most recent call last):
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 703, in <module>
    main()
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: 'module' object has no attribute 'getsitepackages'
Traceback (most recent call last):
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 703, in <module>
    main()
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: 'module' object has no attribute 'getsitepackages'
del /f /q pip_upgrade_py.done
Could Not Find C:\projects\pywbem\pip_upgrade_py.done
python -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 703, in <module>
    main()
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\projects\pywbem\.tox\win64_py27_32\lib\site-packages\win32\lib\pywin32_bootstrap.py", line 14, in <module>
    for maybe in site.getsitepackages():
AttributeError: 'module' object has no attribute 'getsitepackages'
make: *** [makefile:383: pip_upgrade_py.done] Error 1
```

**Comment by andy-maier** [comment]
The same issue has been reported to the `pywin32` project: https://github.com/mhammond/pywin32/issues/1439

**Comment by andy-maier** [comment]
A workaround of pinning the version of pywbem32 to 225 has been provided in PR #1947 for master and TBD for 0.15.0.
