### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by allen0817** [pywbem/pywbem#1950]
hi andy-maier
env 
Python 3.5.7 (default, Aug 16 2019, 10:17:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
pywbem 0.14.0

equipment  : ibm ds8000

code  and error
>>>import pywbem 
>>> conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,None,True)
>>> res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 646, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/local/python3/lib/python3.5/ssl.py", line 1027, in connect
    self._real_connect(addr, False)
  File "/usr/local/python3/lib/python3.5/ssl.py", line 1018, in _real_connect
    self.do_handshake()
  File "/usr/local/python3/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/python3/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] EC lib (_ssl.c:728)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 4196, in ExecQuery
    **extra)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 813, in wbem_request
    client.endheaders()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/python3/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 480, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 651, in connect
    conn_id=conn_id)
pywbem.exceptions.ConnectionError: SSL error <class 'ssl.SSLError'>: [SSL] EC lib (_ssl.c:728)
>>>

**Comment by allen0817** [comment]
ibm v7000  can

**Comment by andy-maier** [comment]
On "ibm v7000 can": Do you want to say that with the v7000, the exception is not raised?

**Comment by andy-maier** [comment]
On the exception you get when using the DS8K: The exception message "[SSL] EC lib (_ssl.c:728)" is not very helpful. I have opened Python issue https://bugs.python.org/issue38810 to get help on it. I can only guess that it has to do with Elliptic Curve. Do you have any special setup there on the system you run pywbem?

**Comment by allen0817** [comment]
nothing other setup,general setup.
reduce the openssl version?
What do you suspect？

**Comment by andy-maier** [comment]
I just double checked the x509 related arguments you specify when creating the WBEMConnection object, and noticed that you are likely setting the arguments incorrectly.

Your code:
```
conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,None,True)
```
probably intends to set `no_verification=True`, but it actually sets it to `no_verification=None` and `timeout=True`, which will cause the pywbem client to verify the certificate received from the server during TLS handshake.

The init arguments are declared as follows:
```
class pywbem.WBEMConnection(url, creds=None, default_namespace=None, x509=None, ca_certs=None, no_verification=False, timeout=None, use_pull_operations=False, stats_enabled=False)
```

-> Can you please remove one `None` from the argument list and see whether it works, i.e.:
```
conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,True)
```

**Comment by allen0817** [comment]
First of all, thank you for your reply, but there is still a mistake, must the certificate?

>>> conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,True)
>>> res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 4196, in ExecQuery
    **extra)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 813, in wbem_request
    client.endheaders()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/python3/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 480, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 633, in connect
    ctx.load_verify_locations(cafile=self.ca_certs)
TypeError: cafile should be a valid filesystem path

or 

>>> conn = pywbem.WBEMConnection('https://192.168.1.10:6989', ('customer', 'cust0mer'), 'root/ibm',None,None,None)
>>> res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 646, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/local/python3/lib/python3.5/ssl.py", line 1027, in connect
    self._real_connect(addr, False)
  File "/usr/local/python3/lib/python3.5/ssl.py", line 1018, in _real_connect
    self.do_handshake()
  File "/usr/local/python3/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/python3/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 4196, in ExecQuery
    **extra)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 813, in wbem_request
    client.endheaders()
  File "/usr/local/python3/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/local/python3/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 480, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/local/python3/lib/python3.5/site-packages/pywbem/cim_http.py", line 651, in connect
    conn_id=conn_id)
pywbem.exceptions.ConnectionError: SSL error <class 'ssl.SSLError'>: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728)
>>>

**Comment by andy-maier** [comment]
It turns out I was wrong with my statement about the WBEMConnection arguments. I was looking at the master branch for this, and there we have meanwhile removed the `verify_callback` argument. In the version 0.14.0 you are using, that parameter still exists and so your original call was correct for that version.

Before pywbem 1.0.0, the interface is:

```
class pywbem.WBEMConnection(url, creds=None, default_namespace=None,
                 x509=None, verify_callback=None, ca_certs=None,
                 no_verification=False, timeout=None, use_pull_operations=False,
                 stats_enabled=False):
```

I'm sorry for the confusion.

**Comment by andy-maier** [comment]
That brings us back to your original issue. I can only speculate here. Lowering the OpenSSL library version may be one thing to try out. Using Wireshark to trace the network traffic during SSL/TLS handshake would also be good.

**Comment by andy-maier** [comment]
@allen0817 Can you please post the version of OpenSSL you are using?

**Comment by KSchopmeyer** [comment]
Karl: Run test on Linux with python 3.5 or 3.6 and determine version of openssl that works.

**Comment by KSchopmeyer** [comment]
Openssl version I normally use on ubuntu environment:

 openssl version -a
OpenSSL 1.1.1  11 Sep 2018
built on: Tue Nov 12 16:58:35 2019 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-kxN_24/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific

**Comment by KSchopmeyer** [comment]
I would initially look for an issue with a particular version of SSL, either on the client or server.

**Comment by allen0817** [comment]
[root@zsacp8 ~]# /usr/local/python3/bin/pip3 list 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
idna (2.8)
linecache2 (1.0.0)
M2Crypto (0.31.0)
ordereddict (1.1)
pbr (4.2.0)
pip (9.0.1)
ply (3.8)
pycrypto (2.6.1)
pywbem (0.14.0)
PyYAML (4.2b4)
requests3 (0.0.0)
setuptools (19.2)
six (1.10.0)
traceback2 (1.4.0)
typing (3.6.6)
unittest2 (1.1.0)
[root@zsacp8 ~]# openssl version
OpenSSL 1.1.1  11 Sep 2018
[root@zsacp8 ~]#

**Comment by allen0817** [comment]
[root@zsacp8 ~]# python3
Python 3.5.7 (default, Aug 16 2019, 10:17:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywbem,ssl,_ssl
>>> pywbem.__version__
'0.14.0'
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.1e-fips 11 Feb 2013'
>>> ssl.OPENSSL_VERSION_INFO
(1, 0, 1, 5, 15)
>>>

**Comment by allen0817** [comment]
I have upgraded the SSL version and it is now an account authentication issue.

>>> conn = pywbem.WBEMConnection('https://10.240.48.140:6989', ('CE', 'serv1cece'), 'root/ibm',None,None,None,True)
>>> res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/zabbix/pack/pywbem-master/pywbem/cim_operations.py", line 4196, in ExecQuery
    **extra)
  File "/usr/local/zabbix/pack/pywbem-master/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/zabbix/pack/pywbem-master/pywbem/cim_http.py", line 858, in wbem_request
    raise AuthError(response.reason, conn_id=conn_id)
pywbem.exceptions.AuthError: Unauthorized
>>> conn = pywbem.WBEMConnection('https://10.240.48.136:6989', ('CE', 'serv1cece'), 'root/ibm',None,None,None,True)
>>> res = conn.ExecQuery('WQL', 'select * from IBMTSSVC_StorageVolume')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/zabbix/pack/pywbem-master/pywbem/cim_operations.py", line 4196, in ExecQuery
    **extra)
  File "/usr/local/zabbix/pack/pywbem-master/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/zabbix/pack/pywbem-master/pywbem/cim_http.py", line 858, in wbem_request
    raise AuthError(response.reason, conn_id=conn_id)
pywbem.exceptions.AuthError: Unauthorized
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1  11 Sep 2018'
>>>

**Comment by andy-maier** [comment]
My first take on that would be that you used the wrong userid/password.

Note that you are using the same IP address as in the original comment, but a different userid/password.

**Comment by allen0817** [comment]
The account problem has been dealt with by IBM engineers and both accounts can log on to the web, but testing smis with both accounts failed

**Comment by andy-maier** [comment]
Ok. So given that the logon worked, I am closing this issue.
Please open a new issue for the failing tests.

**Comment by andy-maier** [comment]
I'm going to add entries in the trouble shooting section to describe these cases.
