### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by kautzy** [pywbem/pywbem#1966]
hi,

i upgraded a system to debian buster. following error occurs when running the check_esxi_hardware.py script. i think a similar ticked was closed a couple of minutes ago... please let me know if i can provide more useful information ;-)

```
root@monitor:/usr/local/src# /usr/local/nagios/libexec/check_esxi_hardware.py -H host2 -U XXXX -P XXXX -v
20191126 17:32:07 LCD Status: True
20191126 17:32:07 Connection to https://host2.vm.xiotron.com
20191126 17:32:07 Found pywbem version 0.14.6
20191126 17:32:07 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pywbem/cim_http.py", line 646, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/lib/python3.7/ssl.py", line 1150, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.7/ssl.py", line 1141, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_esxi_hardware.py", line 720, in <module>
    instance_list = wbemclient.EnumerateInstances(classe)
  File "/usr/local/lib/python3.7/dist-packages/pywbem/cim_operations.py", line 2467, in EnumerateInstances
    **extra)
  File "/usr/local/lib/python3.7/dist-packages/pywbem/cim_operations.py", line 1737, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/lib/python3.7/dist-packages/pywbem/cim_http.py", line 813, in wbem_request
    client.endheaders()
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/dist-packages/pywbem/cim_http.py", line 480, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/local/lib/python3.7/dist-packages/pywbem/cim_http.py", line 651, in connect
    conn_id=conn_id)
pywbem.exceptions.ConnectionError: SSL error <class 'ssl.SSLError'>: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)
```
installed version of pywbem:
```
root@monitor:/# pip3 list | grep pywbem
pywbem           0.14.6
```
installed version of openssl
```
root@monitor:/# openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by andy-maier** [comment]
This is an error that is created by the OpenSSL library and handed back up to the SSL module of Python which hands it up to pywbem. The error indicates that OpenSSL and your WBEM server do not agree about which SSL/TLS protocol level to use.

On Python 3, pywbem specifies `ssl.PROTOCOL_SSLv23` which is an alias for `ssl.PROTOCOL_TLS` which selects the highest protocol version that both the client and server support. Despite the name, this option can select both “SSL” and “TLS” protocols. Bottom line, pywbem tries to not put any additional restrictions on top of the OpenSSL client installation.

On Debian, the OpenSSL 1.1.1 that you are using on the client side has increased the security settings to require at least TLS 1.2. See https://stackoverflow.com/a/53065682/1424462. This means most likely that your server side does not yet support TLS 1.2 or higher.

You can fix this either by lowering the minimum TLS level on the client side (the stackoverflow article mentiones which file to edit), or by making the server side support TLS 1.2

**Comment by kautzy** [comment]
thank you andy. You are right. setting MinProtocol to TLSv1.0 fixed it. cheers!

**Comment by andy-maier** [comment]
I'm going to add an entry in the troubleshooting section to describe this case.
