### ISSUE TITLE
pywbem.yacc.YaccError: Unable to build parser; mof_compiler.py: Syntax error. Expected ':'

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2]
**Symptom:**

Building the file mofparsetab.py fails with the following error:

    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:449: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:518: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:534: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:748: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:761: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:769: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:793: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:1051: Syntax error. Expected ':'
    ERROR: /mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py:1185: Syntax error. Expected ':'
    Traceback (most recent call last):
      File "setup.py", line 32, in <module>
        mof_compiler._build()
      File "/mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/mof_compiler.py", line 1688, in _build
        yacc.yacc(optimize=_optimize, tabmodule=_tabmodule, outputdir=_outputdir)
      File "/mnt/homesmb/Projects/PyWBEM/src-github/repos/pywbem/src/pywbem/yacc.py", line 3027, in yacc
        raise YaccError("Unable to build parser")
    pywbem.yacc.YaccError: Unable to build parser

This can be reproduced with:

    cd src
    rm pywbem/mof*tab.py
    python -B setup.py --version

**Comment by andy-maier** [comment]
**Investigation:**

This is caused by an error introduced (by me) in commit 53ebc0c7 (commit r651 in SourceForge), when cleaning up line lengths in mof_compiler.py. The yacc module included in pywbem does not support breaking the docstrings with the grammar rules into multiple lines, but that is what was done in order to limit the line length to 80.

It turned out that apparently nobody including me had ever deleted the generated mof*tab.py files to recreate them, so the error never surfaced after it was introduced. Because the two generated files are not tracked, they needed to be created again after moving to GitHub, at which point the error surfaced. The error was in all released 0.8.0-dev versions (but was not a problem for consumers of pywbem, because the two generated files are part of the distribution archive).

**Fix:**

Will be fixed by re-establishing the original docstrings in mof_compiler.py.
Will be committed soon.

**Comment by andy-maier** [comment]
This fix has been released in v0.8.0-dev.20151008 (See [dist/pywbem-0.8.0](https://github.com/pywbem/pywbem/tree/master/dist/pywbem-0.8.0) directory).
