### ISSUE TITLE
safety fails to run on cygwin

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2097]
The invocation of the "safety" command during "make check" fails on cygwin:
```
safety check -r minimum-constraints.txt --full-report
Traceback (most recent call last):
  File "/cygdrive/c/projects/pywbem/.tox/cygwin64_py36/bin/safety", line 8, in <module>
    sys.exit(cli())
  File "/cygdrive/c/projects/pywbem/.tox/cygwin64_py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/cygdrive/c/projects/pywbem/.tox/cygwin64_py36/lib/python3.6/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/cygdrive/c/projects/pywbem/.tox/cygwin64_py36/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
make: [makefile:648: safety_py3.6.done] Error 1 (ignored)
```

**Comment by andy-maier** [comment]
Fixed in PRs #2101 for master and #2102 for 0.17.0.
