### ISSUE TITLE
Exceptions during test_client on Ubuntu

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#21]
On the Travis CI system (Ubuntu 12.04) and on Ubuntu 14.04, the test_client unit tests report exceptions, but pass. On RHEL 6.7, they pass without showing exceptions.

Analyze what is happening, and fix, if needed.

The exceptions are (from Travis CI):
(Note that the report line for GetInstance1 gets interrupted by the exceptions)

    Processing YAML file: getinstance.yaml
    Processing test case: GetInstance1: GetInstance sucException in thread Thread-96:
    Traceback (most recent call last):
      File "/opt/python/2.6.9/lib/python2.6/threading.py", line 532, in __bootstrap_inner
        self.run()
      File "/opt/python/2.6.9/lib/python2.6/threading.py", line 484, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/httpretty/core.py", line 637, in fill_filekind
        headers
      File "test_client.py", line 121, in socket_104
        raise socket.error(104, "Connection reset by peer.")
    error: [Errno 104] Connection reset by peer.
    Exception in thread Thread-98:
    Traceback (most recent call last):
      File "/opt/python/2.6.9/lib/python2.6/threading.py", line 532, in __bootstrap_inner
        self.run()
      File "/opt/python/2.6.9/lib/python2.6/threading.py", line 484, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/httpretty/core.py", line 637, in fill_filekind
        headers
      File "test_client.py", line 126, in socket_32
        raise socket.error(32, "Broken pipe.")
    error: [Errno 32] Broken pipe.
    Exception in thread Thread-100:
    Traceback (most recent call last):
      File "/opt/python/2.6.9/lib/python2.6/threading.py", line 532, in __bootstrap_inner
        self.run()
      File "/opt/python/2.6.9/lib/python2.6/threading.py", line 484, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/httpretty/core.py", line 637, in fill_filekind
        headers
      File "test_client.py", line 116, in socket_ssl
        raise socket.sslerror(1, "Arbitrary SSL error.")
    SSLError: [Errno 1] Arbitrary SSL error.
    ceeds
    Processing test case: GetInstance2: GetInstance fails with CIM_ERR_ACCESS_DENIED
    Processing test case: GetInstance3: GetInstance fails with CIM_ERR_INVALID_NAMESPACE (and input params swapped)
    Processing test case: GetInstance4: GetInstance fails with CIM_ERR_INVALID_PARAMETER
    Processing test case: GetInstance5: GetInstance fails with CIM_ERR_INVALID_CLASS
    Processing test case: GetInstance6: GetInstance fails with CIM_ERR_NOT_FOUND
    Processing test case: GetInstance7: GetInstance fails with CIM_ERR_FAILED

**Comment by andy-maier** [comment]
These are actually intended; they are raised by the according testcases, and py.test reports them in a neutral way, that makes it easy to misunderstand them as problems.
Closing as no issue.
