### ISSUE TITLE
dparse 0.5.0 has an infinite recursion issue on Python 2.7

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2139]
Occurs on python 2.7 with dparse 0.5.0 when invoking make check, in the safety command:

```
makefile: Running pyup.io safety check
rm -f safety_py2.7.done
safety check -r minimum-constraints.txt --full-report
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbem27/bin/safety", line 8, in <module>
    sys.exit(cli())
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/safety/cli.py", line 59, in check
    packages = list(itertools.chain.from_iterable(read_requirements(f, resolve=True) for f in files))
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/safety/util.py", line 80, in read_requirements
    req, = parse_line(parseable_line)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/dparse/parser.py", line 62, in setuptools_parse_requirements_backport
    for line in lines:
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/dparse/parser.py", line 58, in yield_lines
    for s in yield_lines(ss):
  . . .
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/dparse/parser.py", line 50, in yield_lines
    if isinstance(strs, str):
RuntimeError: maximum recursion depth exceeded while calling a Python object
make: [safety_py2.7.done] Error 1 (ignored)
```

The issue is also discussed here: see https://github.com/pyupio/dparse/issues/46

**Comment by andy-maier** [comment]
Fixed in PR #2141 for master and #2140 for 0.17.0.
