### ISSUE TITLE
Change in ca_certs parameter

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#2332]
When using a connections file created with pywbem 0.17 we get a load failure in the command pywbmecli -n xxx class enumerate

where the server named xxx has data in the ca-certs parameter.

The following is an example of the connections_file entry that can cause the problem:

    alltypes:
        name: alltypes
        server: null
        user: null
        password: null
        default-namespace: root/cimv2
        timeout: 30
        use_pull: null
        verify: true
        certfile: null
        keyfile: null
        ca-certs:
        - /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
        - /etc/ssl/certs
        - /etc/ssl/certificates
        mock-server:
        - tests/unit/all_types.mof

This produces the following error:

when the pywbemcli command below is executed.:

    pywbemcli -n xxx class enumerate
   (or any command that creates a connection to the server)
   

(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(master)$ ppp -n ophttp qualifier enumerate
Traceback (most recent call last):
  File "/home/kschopmeyer/virtualenvs/pycli3/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_qualifier.py", line 97, in qualifier_enumerate
    context.execute_cmd(lambda: cmd_qualifier_enumerate(context, options))
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 286, in execute_cmd
    cmd()
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_qualifier.py", line 97, in <lambda>
    context.execute_cmd(lambda: cmd_qualifier_enumerate(context, options))
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_qualifier.py", line 130, in cmd_qualifier_enumerate
    qual_decls = sort_cimobjects(context.conn.EnumerateQualifiers(
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 149, in conn
    self._conn = self.wbem_server.conn
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 177, in wbem_server
    verbose=self.verbose)
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_pywbem_server.py", line 502, in create_connection
    stats_enabled=timestats)
  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemtools/pywbemcli/_pywbemcli_operations.py", line 380, in __init__
    super(PYWBEMCLIConnection, self).__init__(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 709, in __init__
    type(self.ca_certs)))
TypeError: The ca_certs parameter has invalid type: <class 'list'>

**Comment by KSchopmeyer** [comment]
CONCLUSION:

The issue occurs because in this particular connection file definition which was created with pywbem 0.xxx WBEMConnections the ca-certs was created with a list of locations for the certs, while the valid definition is either String or None.  How that entry was created I am not sure but it should have been rejected even in pywbem 0.xxx.0

**Comment by KSchopmeyer** [comment]
While there was an issue in pywbem < 1.0.0, actually using the ca_certs with a list, this is a now old version, this was fixed in pywbem 1.0.0 which is what caused the problem with pywbemcli.

**DISCUSSION** should  we consider fixing this?

**Comment by andy-maier** [comment]
I think we should not change the behavior of pywbem<1.0.0 on this. Are you suggesting to add support for a list of path names to pywbem 1.0.0?

**Comment by andy-maier** [comment]
We discussed this today, and the conclusion was that we did support lists of path names before 1.0.0, and that the requests package restricted us to only a single path name. The change history of the 1.0.0 beta versions does not describe that restriction sufficiently, so we should update the list of incompatible changes accordingly.

**Comment by andy-maier** [comment]
Fixed in PR #2346
