### ISSUE TITLE
Improve error handling when receicing invalid CIM-XML response from server

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2512]
The pywbem issue https://github.com/pywbem/pywbemtools/issues/806 is an example where invalid data in the CIM-XML response triggers a TypeError in the tupleparser that goes all the way up to the pywbem API.

This should be improved to clearly identify at the pywbem API that it was an issue with the CIM-XML response, including details to have all data at hand instead of having to ask for reproduction with logging turned on.

**Comment by andy-maier** [comment]
PR #2516 addresses this.

Example for the case of a class path in a key binding, with this fix but without the toleration support added in PR #2515: 

```
Error: Testcase References_InstancesE2: No exception was expected to be raised by PyWBEM operation References, but an exception was actually raised:
Traceback (most recent call last):
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/tests/functiontest/conftest.py", line 891, in runtestcase
    result = op_call(**op_args)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/_cim_operations.py", line 3939, in References
    result = self._imethodcall(
  ...
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/_tupleparse.py", line 1030, in parse_instancename
    raise new_exc
pywbem._exceptions.CIMXMLParseError: Element 'INSTANCENAME' has invalid input for creating a CIMInstanceName object for class 'MY_McsRedundancySetIdentity': Value of keybinding 'SameElement' has an invalid type: <class 'pywbem._cim_obj.CIMClassName'>; CIM-XML tuple tree: ('INSTANCENAME', {'CLASSNAME': 'MY_McsRedundancySetIdentity'}, [' ', ('KEYBINDING', {'NAME': 'SameElement'}, [' ', ('VALUE.REFERENCE', {}, [' ', ('LOCALCLASSPATH', {}, [' ', ('LOCALNAMESPACEPATH', {}, [' ', ('NAMESPACE', {'NAME': 'MyNamespace'}, []), ' ']), ' ', ('CLASSNAME', {'NAME': 'MY_McsControllerRedundancySet'}, []), ' ']), ' ']), ' ']), ' ', ('KEYBINDING', {'NAME': 'SystemElement'}, [' ', ('VALUE.REFERENCE', {}, [' ', ('LOCALINSTANCEPATH', {}, [' ', ('LOCALNAMESPACEPATH', {}, [' ', ('NAMESPACE', {'NAME': 'MyNamespace'}, []), ' ']), ' ', ('INSTANCENAME', {'CLASSNAME': 'MY_Array'}, [' ', ('KEYBINDING', {'NAME': 'CreationClassName'}, [' ', ('KEYVALUE', {'VALUETYPE': 'string'}, ['MY_Array']), ' ']), ' ', ('KEYBINDING', {'NAME': 'Name'}, [' ', ('KEYVALUE', {'VALUETYPE': 'string'}, ['MyArrayName']), ' ']), ' ']), ' ']), ' ']), ' ']), ' '])
```
