### ISSUE TITLE
CIM-XML result parse exception for dell compellent storage

### ISSUE THREAD

**Issue by tanshaolong** [pywbem/pywbem#2540]
Hi everybody,

I have installed pywbem 1.1.2 version. I try to get some associator instances from “CMPL_ComputerSystem” class instance by a dell compellent smi-s provider, but I get bellow exception.

```
>>> sp_insts = conn.Associators(cs_insts[-1].path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 3537, in Associators
    PropertyList=PropertyList)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 1758, in _imethodcall
    tup_tree = tp.parse_cim(tt_)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 410, in parse_cim
    child = self.one_child(tup_tree, ('MESSAGE', 'DECLARATION'))
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 284, in one_child
    return self.parse_any(child)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 2252, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 1814, in parse_message
    'SIMPLEEXPRSP', 'MULTIEXPRSP'))
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 284, in one_child
    return self.parse_any(child)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 2252, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 1966, in parse_simplersp
    child = self.one_child(tup_tree, ('METHODRESPONSE', 'IMETHODRESPONSE'))
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 284, in one_child
    return self.parse_any(child)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 2252, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 2025, in parse_imethodresponse
    ('ERROR', 'IRETURNVALUE', 'PARAMVALUE')))
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 324, in list_of_various
    result.append(self.parse_any(child))
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 2252, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 2111, in parse_ireturnvalue
    'VALUE.INSTANCEWITHPATH'))
  File "/usr/local/lib/python3.6/site-packages/pywbem/_tupleparse.py", line 372, in list_of_same
    conn_id=self.conn_id)
pywbem._exceptions.CIMXMLParseError: Element 'IRETURNVALUE' has unlike child element 'ERROR' (sequence must have like elements 'VALUE.OBJECTWITHPATH')
CIM-XML response: b'<?xml version=\'1.0\' encoding=\'UTF-8\'?><CIM CIMVERSION="2.8" DTDVERSION="2.4"><MESSAGE ID="1001" PROTOCOLVERSION="1.4"><SIMPLERSP><IMETHODRESPONSE NAME="Associators"><IRETURNVALUE><VALUE.OBJECTWITHPATH><INSTANCEPATH><NAMESPACEPATH><HOST>192.168.2.33</HOST><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="compellent"/></LOCALNAMESPACEPATH></NAMESPACEPATH><INSTANCENAME CLASSNAME="CMPL_PhysicalPackage"><KEYBINDING NAME="CreationClassName"><KEYVALUE TYPE="string" VALUETYPE="string">CMPL_PhysicalPackage</KEYVALUE></KEYBINDING><KEYBINDING NAME="Tag"><KEYVALUE TYPE="string" VALUETYPE="string">257060:CMPL_PP</KEYVALUE></KEYBINDING></INSTANCENAME></INSTANCEPATH><INSTANCE CLASSNAME="CMPL_PhysicalPackage"><PROPERTY NAME="Caption" TYPE="string"><VALUE>PhysicalPackage:257060</VALUE></PROPERTY><PROPERTY NAME="SerialNumber" TYPE="string"><VALUE>257060</VALUE></PROPERTY><PROPERTY NAME="ElementName" TYPE="string"><VALUE>257060</VALUE></PROPERTY><PROPERTY NAME="CreationClassName" TYPE="string"><VALUE>CMPL_PhysicalPackage</VALUE></PROPERTY><PROPERTY NAME="Manufacturer" TYPE="string"><VALUE>DELL</VALUE></PROPERTY><PROPERTY NAME="Model" TYPE="string"><VALUE>Storage Center Scv3000Series</VALUE></PROPERTY><PROPERTY NAME="Tag" TYPE="string"><VALUE>257060:CMPL_PP</VALUE></PROPERTY></INSTANCE></VALUE.OBJECTWITHPATH><VALUE.OBJECTWITHPATH><INSTANCEPATH><NAMESPACEPATH><HOST>192.168.2.33</HOST><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="compellent"/></LOCALNAMESPACEPATH></NAMESPACEPATH><INSTANCENAME CLASSNAME="CMPL_ComputerSystem"><KEYBINDING NAME="CreationClassName"><KEYVALUE TYPE="string" VALUETYPE="string">CMPL_ComputerSystem</KEYVALUE></KEYBINDING><KEYBINDING NAME="Name"><KEYVALUE TYPE="string" VALUETYPE="string">257060:257061</KEYVALUE></KEYBINDING></INSTANCENAME></INSTANCEPATH><INSTANCE CLASSNAME="CMPL_ComputerSystem"><PROPERTY NAME="Description" TYPE="string"><VALUE>Controller:257061 Model:Scv3020</VALUE></PROPERTY><PROPERTY NAME="NameFormat" TYPE="string"><VALUE>IP</VALUE></PROPERTY><PROPERTY.ARRAY NAME="OperationalStatus" TYPE="uint16"><VALUE.ARRAY><VALUE>6</VALUE></VALUE.ARRAY></PROPERTY.ARRAY><PROPERTY.ARRAY NAME="Dedicated" TYPE="uint16"><VALUE.ARRAY><VALUE>0</VALUE></VALUE.ARRAY></PROPERTY.ARRAY><PROPERTY NAME="Name" TYPE="string"><VALUE>257060:257061</VALUE></PROPERTY><PROPERTY NAME="ElementName" TYPE="string"><VALUE>257061</VALUE></PROPERTY><PROPERTY NAME="CreationClassName" TYPE="string"><VALUE>CMPL_ComputerSystem</VALUE></PROPERTY><PROPERTY.ARRAY NAME="StatusDescriptions" TYPE="string"><VALUE.ARRAY><VALUE>Down</VALUE></VALUE.ARRAY></PROPERTY.ARRAY><PROPERTY NAME="HealthState" TYPE="uint16"><VALUE>25</VALUE></PROPERTY></INSTANCE></VALUE.OBJECTWITHPATH><VALUE.OBJECTWITHPATH><INSTANCEPATH><NAMESPACEPATH><HOST>192.168.2.33</HOST><LOCALNAMESPACEPATH><NAMESPACE NAME="root"/><NAMESPACE NAME="compellent"/></LOCALNAMESPACEPATH></NAMESPACEPATH><INSTANCENAME CLASSNAME="CMPL_ComputerSystem"><KEYBINDING NAME="CreationClassName"><KEYVALUE TYPE="string" VALUETYPE="string">CMPL_ComputerSystem</KEYVALUE></KEYBINDING><KEYBINDING NAME="Name"><KEYVALUE TYPE="string" VALUETYPE="string">257060:257060</KEYVALUE></KEYBINDING></INSTANCENAME></INSTANCEPATH><INSTANCE CLASSNAME="CMPL_ComputerSystem"><PROPERTY NAME="Description" TYPE="string"><VALUE>Controller:257060 Model:Scv3020</VALUE></PROPERTY><PROPERTY NAME="NameFormat" TYPE="string"><VALUE>IP</VALUE></PROPERTY><PROPERTY.ARRAY NAME="OperationalStatus" TYPE="uint16"><VALUE.ARRAY><VALUE>6</VALUE></VALUE.ARRAY></PROPERTY.ARRAY><PROPERTY.ARRAY NAME="Dedicated" TYPE="uint16"><VALUE.ARRAY><VALUE>0</VALUE></VALUE.ARRAY></PROPERTY.ARRAY><PROPERTY NAME="Name" TYPE="string"><VALUE>257060:257060</VALUE></PROPERTY><PROPERTY NAME="ElementName" TYPE="string"><VALUE>257060</VALUE></PROPERTY><PROPERTY NAME="CreationClassName" TYPE="string"><VALUE>CMPL_ComputerSystem</VALUE></PROPERTY><PROPERTY.ARRAY NAME="StatusDescriptions" TYPE="string"><VALUE.ARRAY><VALUE>Down</VALUE></VALUE.ARRAY></PROPERTY.ARRAY><PROPERTY NAME="HealthState" TYPE="uint16"><VALUE>25</VALUE></PROPERTY></INSTANCE></VALUE.OBJECTWITHPATH><ERROR CODE="1" DESCRIPTION="java.lang.RuntimeException: "/></IRETURNVALUE></IMETHODRESPONSE></SIMPLERSP></MESSAGE></CIM>'
```

I transfer the cim-xml to human-readable format. 
```
<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<CIM CIMVERSION="2.8" DTDVERSION="2.4">
    <MESSAGE ID="1001" PROTOCOLVERSION="1.4">
        <SIMPLERSP>
            <IMETHODRESPONSE NAME="Associators">
                <IRETURNVALUE>
                    <VALUE.OBJECTWITHPATH>
                        <INSTANCEPATH>
                            <NAMESPACEPATH>
                                <HOST>192.168.2.33</HOST>
                                <LOCALNAMESPACEPATH>
                                    <NAMESPACE NAME="root"/>
                                    <NAMESPACE NAME="compellent"/>
                                </LOCALNAMESPACEPATH>
                            </NAMESPACEPATH>
                            <INSTANCENAME CLASSNAME="CMPL_PhysicalPackage">
                                <KEYBINDING NAME="CreationClassName">
                                    <KEYVALUE TYPE="string" VALUETYPE="string">CMPL_PhysicalPackage</KEYVALUE>
                                </KEYBINDING>
                                <KEYBINDING NAME="Tag">
                                    <KEYVALUE TYPE="string" VALUETYPE="string">257060:CMPL_PP</KEYVALUE>
                                </KEYBINDING>
                            </INSTANCENAME>
                        </INSTANCEPATH>
                        <INSTANCE CLASSNAME="CMPL_PhysicalPackage">
                            <PROPERTY NAME="Caption" TYPE="string">
                                <VALUE>PhysicalPackage:257060</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="SerialNumber" TYPE="string">
                                <VALUE>257060</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="ElementName" TYPE="string">
                                <VALUE>257060</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="CreationClassName" TYPE="string">
                                <VALUE>CMPL_PhysicalPackage</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="Manufacturer" TYPE="string">
                                <VALUE>DELL</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="Model" TYPE="string">
                                <VALUE>Storage Center Scv3000Series</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="Tag" TYPE="string">
                                <VALUE>257060:CMPL_PP</VALUE>
                            </PROPERTY>
                        </INSTANCE>
                    </VALUE.OBJECTWITHPATH>
                    <VALUE.OBJECTWITHPATH>
                        <INSTANCEPATH>
                            <NAMESPACEPATH>
                                <HOST>192.168.2.33</HOST>
                                <LOCALNAMESPACEPATH>
                                    <NAMESPACE NAME="root"/>
                                    <NAMESPACE NAME="compellent"/>
                                </LOCALNAMESPACEPATH>
                            </NAMESPACEPATH>
                            <INSTANCENAME CLASSNAME="CMPL_ComputerSystem">
                                <KEYBINDING NAME="CreationClassName">
                                    <KEYVALUE TYPE="string" VALUETYPE="string">CMPL_ComputerSystem</KEYVALUE>
                                </KEYBINDING>
                                <KEYBINDING NAME="Name">
                                    <KEYVALUE TYPE="string" VALUETYPE="string">257060:257061</KEYVALUE>
                                </KEYBINDING>
                            </INSTANCENAME>
                        </INSTANCEPATH>
                        <INSTANCE CLASSNAME="CMPL_ComputerSystem">
                            <PROPERTY NAME="Description" TYPE="string">
                                <VALUE>Controller:257061 Model:Scv3020</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="NameFormat" TYPE="string">
                                <VALUE>IP</VALUE>
                            </PROPERTY>
                            <PROPERTY.ARRAY NAME="OperationalStatus" TYPE="uint16">
                                <VALUE.ARRAY>
                                    <VALUE>6</VALUE>
                                </VALUE.ARRAY>
                            </PROPERTY.ARRAY>
                            <PROPERTY.ARRAY NAME="Dedicated" TYPE="uint16">
                                <VALUE.ARRAY>
                                    <VALUE>0</VALUE>
                                </VALUE.ARRAY>
                            </PROPERTY.ARRAY>
                            <PROPERTY NAME="Name" TYPE="string">
                                <VALUE>257060:257061</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="ElementName" TYPE="string">
                                <VALUE>257061</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="CreationClassName" TYPE="string">
                                <VALUE>CMPL_ComputerSystem</VALUE>
                            </PROPERTY>
                            <PROPERTY.ARRAY NAME="StatusDescriptions" TYPE="string">
                                <VALUE.ARRAY>
                                    <VALUE>Down</VALUE>
                                </VALUE.ARRAY>
                            </PROPERTY.ARRAY>
                            <PROPERTY NAME="HealthState" TYPE="uint16">
                                <VALUE>25</VALUE>
                            </PROPERTY>
                        </INSTANCE>
                    </VALUE.OBJECTWITHPATH>
                    <VALUE.OBJECTWITHPATH>
                        <INSTANCEPATH>
                            <NAMESPACEPATH>
                                <HOST>192.168.2.33</HOST>
                                <LOCALNAMESPACEPATH>
                                    <NAMESPACE NAME="root"/>
                                    <NAMESPACE NAME="compellent"/>
                                </LOCALNAMESPACEPATH>
                            </NAMESPACEPATH>
                            <INSTANCENAME CLASSNAME="CMPL_ComputerSystem">
                                <KEYBINDING NAME="CreationClassName">
                                    <KEYVALUE TYPE="string" VALUETYPE="string">CMPL_ComputerSystem</KEYVALUE>
                                </KEYBINDING>
                                <KEYBINDING NAME="Name">
                                    <KEYVALUE TYPE="string" VALUETYPE="string">257060:257060</KEYVALUE>
                                </KEYBINDING>
                            </INSTANCENAME>
                        </INSTANCEPATH>
                        <INSTANCE CLASSNAME="CMPL_ComputerSystem">
                            <PROPERTY NAME="Description" TYPE="string">
                                <VALUE>Controller:257060 Model:Scv3020</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="NameFormat" TYPE="string">
                                <VALUE>IP</VALUE>
                            </PROPERTY>
                            <PROPERTY.ARRAY NAME="OperationalStatus" TYPE="uint16">
                                <VALUE.ARRAY>
                                    <VALUE>6</VALUE>
                                </VALUE.ARRAY>
                            </PROPERTY.ARRAY>
                            <PROPERTY.ARRAY NAME="Dedicated" TYPE="uint16">
                                <VALUE.ARRAY>
                                    <VALUE>0</VALUE>
                                </VALUE.ARRAY>
                            </PROPERTY.ARRAY>
                            <PROPERTY NAME="Name" TYPE="string">
                                <VALUE>257060:257060</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="ElementName" TYPE="string">
                                <VALUE>257060</VALUE>
                            </PROPERTY>
                            <PROPERTY NAME="CreationClassName" TYPE="string">
                                <VALUE>CMPL_ComputerSystem</VALUE>
                            </PROPERTY>
                            <PROPERTY.ARRAY NAME="StatusDescriptions" TYPE="string">
                                <VALUE.ARRAY>
                                    <VALUE>Down</VALUE>
                                </VALUE.ARRAY>
                            </PROPERTY.ARRAY>
                            <PROPERTY NAME="HealthState" TYPE="uint16">
                                <VALUE>25</VALUE>
                            </PROPERTY>
                        </INSTANCE>
                    </VALUE.OBJECTWITHPATH>
                    <ERROR CODE="1" DESCRIPTION="java.lang.RuntimeException: "/>
                </IRETURNVALUE>
            </IMETHODRESPONSE>
        </SIMPLERSP>
    </MESSAGE>
</CIM>
```
I can find the “VALUE.OBJECTWITHPATH” elements. Is this a pywbem issue? Or is this a Dell smi-s provider issue? Who could give me some help? 

Ray
Thank you

**Comment by tanshaolong** [comment]
Sorry, I think that it is smi-s provider exception. I missed error message "<ERROR CODE="1" DESCRIPTION="java.lang.RuntimeException: "/>" at the cim-xml result.  You could help close it. Sorry for it again.

**Comment by andy-maier** [comment]
Sorry for the delay. This is definitely an issue on the server side. The server side returns an `ERROR` element as a child element of `VALUE.OBJECTWITHPATH`. That is not allowed, see section 5.3.3.8 "VALUE.OBJECTWITHPATH" in [DSP0201](https://www.dmtf.org/sites/default/files/standards/documents/DSP0201_2.4.0.pdf).

Closing this issue.
