### ISSUE TITLE
RecursionError raised by flake8 on Python 3.6 and 3.7

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#2922]
From https://github.com/pywbem/pywbem/actions/runs/3120734938/jobs/5062224973 :

```
flake8 --version
5.0.3 (mccabe: 0.7.0, pycodestyle: 2.9.1, pyflakes: 2.5.0) CPython 3.7.14 on
Linux
flake8 --statistics --config=.flake8 --filename='*' setup.py pywbem/_exceptions.py pywbem/_recorder.py pywbem/config.py pywbem/_listener.py pywbem/_cim_operations.py pywbem/_cliutils.py pywbem/__init__.py pywbem/_server.py pywbem/_mof_compiler.py pywbem/_cim_obj.py pywbem/_cim_http.py pywbem/_warnings.py pywbem/_statistics.py pywbem/_version.py pywbem/_tupleparse.py pywbem/_cim_constants.py pywbem/_features.py pywbem/_units.py pywbem/_cim_types.py pywbem/_logging.py pywbem/_cim_xml.py pywbem/_valuemapping.py pywbem/_subscription_manager.py pywbem/_nocasedict.py pywbem/_tupletree.py pywbem/_utils.py pywbem_mock/_mockmofwbemconnection.py pywbem_mock/_providerregistry.py pywbem_mock/_instancewriteprovider.py pywbem_mock/__init__.py pywbem_mock/_resolvermixin.py pywbem_mock/_baseprovider.py pywbem_mock/_inmemoryrepository.py pywbem_mock/_baserepository.py pywbem_mock/_dmtf_cim_schema.py pywbem_mock/_providerdependentregistry.py pywbem_mock/_methodprovider.py pywbem_mock/_wbemconnection_mock.py pywbem_mock/_utils.py pywbem_mock/_providerdispatcher.py pywbem_mock/config.py pywbem_mock/_mainprovider.py pywbem_mock/_subscriptionproviders.py pywbem_mock/_namespaceprovider.py mof_compiler  tests/utils.py tests/__init__.py tests/elapsed_timer.py tests/leaktest/test_leaks_elementtree.py tests/leaktest/test_leaks_cim_obj.py tests/leaktest/__init__.py tests/leaktest/test_leaks_minidom.py tests/leaktest/test_leaks_cim_xml.py tests/leaktest/test_leaks_statistics.py tests/leaktest/test_leaks_dict.py tests/perftest/test_indications.py tests/perftest/__init__.py tests/end2endtest/test_profile_snia_smis.py tests/end2endtest/test_profile_generic.py tests/end2endtest/test_server.py tests/end2endtest/__init__.py tests/end2endtest/test_profile_snia_server.py tests/resourcetest/timers.py tests/resourcetest/random_objects.py tests/resourcetest/test_enuminst.py tests/resourcetest/__init__.py tests/resourcetest/resource_measurement.py tests/resourcetest/memory_utils.py tests/unittest/__init__.py tests/manualtest/run_enum_performancesimple.py tests/manualtest/run_response_performance.py tests/manualtest/run_enum_performance.py tests/manualtest/run_uprint.py tests/manualtest/run_cim_operations.py tests/manualtest/__init__.py tests/manualtest/run_operationtimeouts.py tests/functiontest/conftest.py tests/functiontest/__init__.py tests/end2endtest/utils/utils.py tests/end2endtest/utils/pytest_extensions.py tests/end2endtest/utils/assertions.py tests/end2endtest/utils/__init__.py tests/unittest/pywbem_mock/test_complexassoc.py tests/unittest/pywbem_mock/conftest.py tests/unittest/pywbem_mock/test_providerregistry.py tests/unittest/pywbem_mock/test_inmemory_repository.py tests/unittest/pywbem_mock/__init__.py tests/unittest/pywbem_mock/test_multi_ns_assoc.py tests/unittest/pywbem_mock/test_providerdependentregistry.py tests/unittest/pywbem_mock/test_wbemconnection_mock.py tests/unittest/pywbem_mock/test_system_providers.py tests/unittest/end2endtest_utils/__init__.py tests/unittest/unittest_utils/__init__.py tests/unittest/resourcetest/test_memory_utils.py tests/unittest/resourcetest/__init__.py tests/unittest/utils/validate.py tests/unittest/utils/wbemserver_mock.py tests/unittest/utils/unichr2.py tests/unittest/utils/dmtf_mof_schema_def.py tests/unittest/utils/pytest_extensions.py tests/unittest/utils/__init__.py tests/unittest/utils/unittest_extensions.py tests/unittest/functiontest/__init__.py tests/unittest/functiontest/test_conftest.py tests/unittest/pywbem/test_logging.py tests/unittest/pywbem/test_cim_xml.py tests/unittest/pywbem/test_valuemapping.py tests/unittest/pywbem/test_subscriptionmanager.py tests/unittest/pywbem/test_nocasedict.py tests/unittest/pywbem/test_tupletree.py tests/unittest/pywbem/test_cim_operations.py tests/unittest/pywbem/test_exceptions.py tests/unittest/pywbem/test_wbemserverclass.py tests/unittest/pywbem/test_indicationlistener.py tests/unittest/pywbem/test_statistics.py tests/unittest/pywbem/test_mof_compiler.py tests/unittest/pywbem/__init__.py tests/unittest/pywbem/test_perf_equality.py tests/unittest/pywbem/test_cim_obj.py tests/unittest/pywbem/test_cim_http.py tests/unittest/pywbem/test_warnings.py tests/unittest/pywbem/test_itermethods.py tests/unittest/pywbem/test_tupleparse.py tests/unittest/pywbem/test_units.py tests/unittest/pywbem/test_cim_types.py tests/unittest/pywbem/test_recorder.py tests/unittest/pywbem/test_utils.py  
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 336, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 325, in _run
    self.run_checks()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 229, in run_checks
    self.file_checker_manager.run()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/checker.py", line 250, in run
    self.run_parallel()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/checker.py", line 217, in run_parallel
    for ret in pool_map:
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/collections/__init__.py", line 432, in __getnewargs__
    return tuple(self)
RecursionError: maximum recursion depth exceeded
```

**Comment by andy-maier** [comment]
It turns out the RecursionError was fixed in flake8 5.0.4 (see https://flake8.pycqa.org/en/latest/release-notes/5.0.4.html#bugs-fixed).

However, pip does not install flake8 5.0.4 and remains on 5.0.3. This is caused by a pinning of importlib-metadata<1 for Python<=3.7 in our test-requirements.txt file, and pip selects a flake8 version that satisfies that constraint.

But the story with importlib-metadata versions and flake8 is larger: flake8>4.0.0 pins importlib-metadata<4.3 on Python<3.8, and does not plan to lift that pinning (see https://github.com/PyCQA/flake8/pull/1438), and does also not plan to switch to the replacement API of importlib-metadata. That pinning causes version conflicts with the versions of Sphinx and virtualenv we are using, both of which require importlib-metadata>=4.8.x.

Since the pinning of importlib-metadata<4.3 in flake8 is only for Python<3.8, this issue will resolve itself in the future as Python versions move forward, so I think the strategy for us is either one of these options:
* Focus on new Sphinx and virtualenv: pin flake8<4.0 on Python<3.8 since these versions do not pin importlib-metadata yet
* Focus on new flake8: pin Sphinx and virtualenv on Python<3.8 to versions that do not require importlib-metadata>4.3

It turns out that the virtualenv 20.0.35 version we are currently using is the minimum version required by "build", and we certainly do not want to use different package build tools depending on Python versions. That excludes the second option, above.
