### ISSUE TITLE
Pywbem install with Pyth0on 3.12 fails, pkgutil Impimporter class not found

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#3101]
setup.py fails because package pkgutil no does not contain deprecated ImpImporter class.

```
Ignoring certifi: markers 'python_version == "2.7"' don't match your environment
Collecting ply>=3.10 (from -r requirements.txt (line 13))
  Downloading ply-3.10.tar.gz (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.9/150.9 kB 5.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:455: done/install_pywbem_py3.12_minimum.done] Error 1
Error: Process completed with exit code 2.

```

This is a python 3.12 issue and is commented on in a number of posts including:

https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

https://github.com/pypa/pip/issues/12179

**Comment by KSchopmeyer** [comment]
Duplicate of issue #3101.  Closing
