### ISSUE TITLE
pywbem 1.7.0/1 install issue with ImportError on Python 2.7

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#3163]
pywbem 1.7.0 and 1.7.1 do not install on Python 2.7 when used from Pypi.

From https://github.com/pywbem/pywbemtools/actions/runs/8735353484/job/23968155012:

```
python -c "import pywbemtools.pywbemcli"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pywbemtools/pywbemcli/__init__.py", line 28, in <module>
    from .._output_formatting import *    # noqa: F403,F401
  File "pywbemtools/_output_formatting.py", line 36, in <module>
    from pywbem import CIMInstanceName
  File "/usr/local/lib/python2.7/site-packages/pywbem/__init__.py", line 49, in <module>
    from ._cim_operations import *  # noqa: F403,F401
  File "/usr/local/lib/python2.7/site-packages/pywbem/_cim_operations.py", line 158, in <module>
    from ._nocasedict import NocaseDict
  File "/usr/local/lib/python2.7/site-packages/pywbem/_nocasedict.py", line 43, in <module>
    from ._vendor.nocasedict import NocaseDict as _NocaseDict
ImportError: No module named _vendor.nocasedict
```

Looking at the distribution wheel archive for 1.7.0 and 1.7.1, it turns out that the `pywbem/_vendor/__init__.py` file is missing from the archive, and that is the reason. Apparently Python 3 can do the import without that, but Python 2 cannot.

It is yet to be clarified why the install test of pywbem on Python 2.7 did not find that.

**Comment by andy-maier** [comment]
The reason the install test did not catch this was that it was run in the main repo directory. So the import test used the package from that directory, instead of taking it from the installed package. That test is also fixed in the PR.
