### ISSUE TITLE
timeout of https connection generates incorrect exception

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#363]
A timeout of an https connection causes a a certificate error exception, not a socket error exception.

**Comment by andy-maier** [comment]
What is the exact exception class?

**Comment by KSchopmeyer** [comment]
Something changed.  I am creating a pr now with example of error.  It is not a cert error but an issue in m2crypto at this point.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/httpretty/core.py", line 637, in fill_filekind
    headers
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/testsuite/test_client.py", line 217, in socket_timeout
    raise socket.timeout("Socket timeout.")
timeout: Socket timeout.

Exception AttributeError: "Connection instance has no attribute 'ssl_close_flag'" in <bound method Connection.__del__ of <M2Crypto.SSL.Connection.Connection instance at 0x2afff0369290>> ignored

see pr #376
