### ISSUE TITLE
Issue with server class and NocaseDict initialization in python3

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#393]
The following issue is peculiar to python 3.   It occurs in both examples/explore.py and what I added
as tests for run_cim_operations testing the server class.   I can only assume that I have been less than diligent in testing against both python 2 and python 3 the last few days.

All this runs fine against python 2.7. At first I thought it was the new code I added for issue #378 but the explore.py example is in the brand property which has not been modified recently.

```
(pywbem3)kschopmeyer@sheldon:~/pywbem/githubpywbem/pywbem/examples$ ./explore.py http://sheldon ks ks
WBEM server URL:
  http://sheldon
Traceback (most recent call last):
  File "./explore.py", line 101, in <module>
    sys.exit(main())
  File "./explore.py", line 96, in main
    explore_server(server_url, username, password)
  File "./explore.py", line 27, in explore_server
    print("Brand:\n  %s" % server.brand)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 264, in brand
    self._determine_brand()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 670, in _determine_brand
    "CIM_ObjectManager", namespace=self.interop_ns)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 203, in interop_ns
    self._determine_interop_ns()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 557, in _determine_interop_ns
    ns_dict = NocaseDict(zip(ns_names, ns_names))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_obj.py", line 171, in __init__
    repr(args[0]))
TypeError: Invalid type for NocaseDict initialization: <zip object at 0x7fb9e7a66c08>
```

------- same error with cim_run_operations.py
```
Traceback (most recent call last):
  File "./testsuite/run_cim_operations.py", line 2846, in test_server_select_profiles
    org_vm = ValueMapping.for_property(server, server.interop_ns,
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 203, in interop_ns
    self._determine_interop_ns()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 557, in _determine_interop_ns
    ns_dict = NocaseDict(zip(ns_names, ns_names))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_obj.py", line 171, in __init__
    repr(args[0]))
TypeError: Invalid type for NocaseDict initialization: <zip object at 0x7f3d11af83c8>
```

**Edited** for better representation of messages.

**Comment by andy-maier** [comment]
This is another case where the %s does not work for you.

What happens if you change the `repr(args[0])` to `args[0].__class__.__name__` ?

**Comment by KSchopmeyer** [comment]
Found this helpful ??? tidbit


down vote
In python 2.7 this might have worked fine.

>>> a=b=c=range(20)
>>> zip(a,b,c)

But in python 3.4

>>> a=b=c=range(20)
>>> list(zip(a,b,c))

In Python 2, the global zip() function took any number of sequences and returned a list of tuples. The first tuple contained the first item from each sequence; the second tuple contained the second item from each sequence; and so on. In Python 3, zip() returns an iterator instead of a list.

**Comment by andy-maier** [comment]
I edited the output above to make it shown as examples, because not doing so makes Markdown suppress the type name. That is the solution to the miracle of the lost %s output ;-)

**Comment by andy-maier** [comment]
Solution is to use an extra `list()`, as you hinted.
