### ISSUE TITLE
HTTPError not defined error in cim_http.py

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#415]
Traceback (most recent call last):
  File "testsuite/run_cim_operations.py", line 1736, in test_propertylist_tuple
    LocalOnly=False)
  File "testsuite/run_cim_operations.py", line 114, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 3585, in GetInstance
    **extra)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 766, in _imethodcall
    recorder=self.operation_recorder)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 826, in wbem_request
    raise HTTPError(response.status, response.reason, cimerror_hdr, cimdetails)
NameError: global name 'HTTPError' is not defined

**Comment by andy-maier** [comment]
Addressed in PR #416.
