### ISSUE TITLE
Getting leakthrough of ssl error exceptions.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#435]
When running with python 3 against a varietly of servers, we get the following from at least some servers

url=https://10.1.134.252 credential=smilab, principal=F00sb4ll
WBEM server URL:  https://10.1.134.252
Traceback (most recent call last):
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 574, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/lib/python3.4/ssl.py", line 864, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.4/ssl.py", line 855, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSL_NEGATIVE_LENGTH] dh key too small (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./explore.py", line 196, in main
    explore_server(url, principal, credential, args)
  File "/home/kschopmeyer/Dropbox/work/pyping/pyping/timeout.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "./explore.py", line 74, in explore_server
    print('interop=%s' % server.interop_ns)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 202, in interop_ns
    self._determine_interop_ns()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 539, in _determine_interop_ns
    namespace=ns)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 1275, in EnumerateInstanceNames
    **extra)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 770, in _imethodcall
    recorder=self.operation_recorder)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 730, in wbem_request
    client.endheaders()
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 418, in send
    self.connect()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 578, in connect
    "SSL error %s: %s" % (arg.__class__, arg))
pywbem.exceptions.ConnectionError: SSL error <class 'ssl.SSLError'>: [SSL: SSL_NEGATIVE_LENGTH] dh key too small (_ssl.c:600)

**Comment by KSchopmeyer** [comment]
There are two issues here

1. Why are we getting an ssl error bled through PyWBEM

2. Why are we getting the original error.  That is apparently a Python error (3.4, 3.5, 2.7) with some ssl packages.  See Python bug https://bugs.python.org/issue23844 "test_ssl: fails on recent libressl version with BAD_DH_P_LENGTH".  There is patch for this issue apparently but since this is from 2015, not sure about status now.

**Comment by andy-maier** [comment]
I suggest that we scope this issue to the issue that the `SSLError` comes up (issue 1 in the list above).

I looked at the source code, and the particular piece of code that is referenced in the `SSLError` traceback in your original report above, is (meanwhile the `connect()` call is on line 596):

```
                try:
                    self.sock = ctx.wrap_socket(sock,
                                                server_hostname=self.host)
                    return self.sock.connect((self.host, self.port))

                except SSLError as arg:
                    raise ConnectionError(
                        "SSL error %s: %s" % (arg.__class__, arg))
                except CertificateError as arg:
                    raise ConnectionError(
                        "SSL certificate error %s: %s" % (arg.__class__, arg))
```

So this code catches any `SSLError` and raises a `pywbem.ConnectionError` for it. `SSLError` is from the `ssl` module of Python 3.

It is not clear to me how the traceback for `SSLError` could have happened at all.

I guess this asks for a reproduction of the problem, if possible.
