### ISSUE TITLE
Double timeout when connected to certain servers.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#442]
At least one server in our testing returns first a ConnectionError and then, apparently a Timeout error on the same operation.  The trace is the following:

```
url=http://10.1.132.227, company=Hewlett Packard product=P2000 G3 MSA
Traceback (most recent call last):
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 744, in wbem_request
    response = client.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 849, in wbem_request
    raise ConnectionError("The server closed the "\
pywbem.exceptions.ConnectionError: The server closed the connection without returning any data, or the client timed out
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "./explore.py", line 280, in <module>
    sys.exit(main())
  File "./explore.py", line 274, in main
    versions = smi_version(server_tuple[1])
  File "./explore.py", line 76, in smi_version
    snia_server_profiles = server.get_selected_profiles('SNIA','SMI-S')
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 336, in get_selected_profiles
    for inst in self.profiles:
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 298, in profiles
    self._determine_profiles()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_server.py", line 718, in _determine_profiles
    namespace=self.interop_ns)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 1443, in EnumerateInstances
    **extra)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 770, in _imethodcall
    recorder=self.operation_recorder)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 862, in wbem_request
    break
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_http.py", line 201, in __exit__
    "socket after %.0fs." % duration_sec)
pywbem.exceptions.TimeoutError: The client timed out and closed the socket after 20s.
```

**Comment by KSchopmeyer** [comment]
We agreed to close this one as no examples found in the last year of testing after other changes made to the exception code.
