### ISSUE TITLE
Python 3, _recorder Type error in building output

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#531]
When running run_cimoperations.py with python 3 I hit the following exception in the recorder.

```
Traceback (most recent call last):
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 4025, in DeleteInstance
    **extra)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 865, in _imethodcall
    raise CIMError(code, err[1]['DESCRIPTION'])
pywbem.exceptions.CIMError: 5: CIM_ERR_INVALID_CLASS: PyWBEM_Person

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_cim_operations.py", line 1829, in test_all
    self.cimcall(self.conn.DeleteInstance, instance.path)
  File "./run_cim_operations.py", line 130, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 4030, in DeleteInstance
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/_recorder.py", line 296, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/_recorder.py", line 431, in record
    data = http_response.payload.replace("\n\n", "\n")
TypeError: 'str' does not support the buffer interface
```
In python 3 the Type for the payload is bytes, not str.

**Comment by KSchopmeyer** [comment]
This is a python 3 issue in that with python 2.7 it works fine.


I tried some fixes. Modified the output to pass those things that are b' through toyaml function and that eliminated the bytes components.

However, It still failed at the yaml.safe_dump:
======================================================================
ERROR: test_all (__main__.CreateInstance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 4025, in DeleteInstance
    **extra)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 865, in _imethodcall
    raise CIMError(code, err[1]['DESCRIPTION'])
pywbem.exceptions.CIMError: 5: CIM_ERR_INVALID_CLASS: PyWBEM_Person

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_cim_operations.py", line 1828, in test_all
    self.cimcall(self.conn.DeleteInstance, instance.path)
  File "./run_cim_operations.py", line 129, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 4030, in DeleteInstance
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/_recorder.py", line 296, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.10.0.dev0-py3.4.egg/pywbem/_recorder.py", line 450, in record
    default_flow_style=False))
TypeError: must be str, not bytes


To see what the issue in the testcase was I then commented out the various functions that append to the testcase until they were all commented out so that the test case displays as:

testcase OrderedDict()

Still fails in yaml.safe_dump(...) so I put it aside for the moment.

Here are the patches I applied:

```
--- /tmp/52MTEl__recorder.py
+++ /home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py
@@ -371,8 +371,8 @@
         """
 
         testcase = OrderedDict()
-        testcase['name'] = pywbem_args.method
-        testcase['description'] = 'Generated by TestClientRecorder'
+        #testcase['name'] = pywbem_args.method
+        #testcase['description'] = 'Generated by TestClientRecorder'
 
         tc_pywbem_request = OrderedDict()
         tc_pywbem_request['url'] = TestClientRecorder.TESTCASE_URL
@@ -386,7 +386,7 @@
         for arg_name in pywbem_args.args:
             tc_operation[arg_name] = self.toyaml(pywbem_args.args[arg_name])
         tc_pywbem_request['operation'] = tc_operation
-        testcase['pywbem_request'] = tc_pywbem_request
+        #testcase['pywbem_request'] = tc_pywbem_request
 
         tc_pywbem_response = OrderedDict()
         if pywbem_result.ret is not None:
@@ -398,7 +398,7 @@
             else:
                 tc_pywbem_response['exception'] = self.toyaml(
                     exc.__class__.__name__)
-        testcase['pywbem_response'] = tc_pywbem_response
+        #testcase['pywbem_response'] = tc_pywbem_response
 
         tc_http_request = OrderedDict()
         if http_request is not None:
@@ -413,22 +413,25 @@
                         tc_request_headers[hdr_name] = \
                             http_request.headers[hdr_name]
             tc_http_request['headers'] = tc_request_headers
-            tc_http_request['data'] = http_request.payload
-        testcase['http_request'] = tc_http_request
+            tc_http_request['data'] = self.toyaml(http_request.payload)
+        #testcase['http_request'] = tc_http_request
 
         tc_http_response = OrderedDict()
         if http_response is not None:
+            print('type status %s' % type(http_response.status))
             tc_http_response['status'] = http_response.status
             tc_response_headers = OrderedDict()
             if http_response.headers is not None:
                 for hdr_name in http_response.headers:
+                    print('type hdr %s' % type(http_response.status))
                     if hdr_name.lower() not in \
                        TestClientRecorder.EXCLUDE_RESPONSE_HEADERS:
                         tc_response_headers[hdr_name] = \
-                            http_response.headers[hdr_name]
+                            self.toyaml(http_response.headers[hdr_name])
             tc_http_response['headers'] = tc_response_headers
             if http_response.payload is not None:
-                data = http_response.payload.replace("\n\n", "\n")
+                payload_str = self.toyaml(http_response.payload)
+                data = payload_str.replace("\n\n", "\n")
             else:
                 data = None
             tc_http_response['data'] = data
@@ -436,8 +439,8 @@
             tc_http_response['exception'] = "# Change this to a callback " \
                                             "function that causes this " \
                                             "condition."
-        testcase['http_response'] = tc_http_response
-
+        #testcase['http_response'] = tc_http_response
+        print('testcase %s' % testcase)
         testcases = []
         testcases.append(testcase)

```
