### ISSUE TITLE
qualifierdecl to cimxml fails

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#645]
The following qualifierdecl:

        scopes = self._build_scope(set_true=['CLASS'])
        qd = CIMQualifierDeclaration('FooQualDecl', 'string', is_array=True,
                                     value='Some string',
                                     array_size=4, scopes=scopes,
                                     overridable=False, tosubclass=True,
                                     toinstance=True, translatable=False)

Fails the SetQualifier cim_operation request with the following error.
Traceback (most recent call last):
  File "testsuite/run_cim_operations.py", line 3477, in test_create_delete
    self.cimcall(self.conn.SetQualifier, qd)
  File "testsuite/run_cim_operations.py", line 153, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_operations.py", line 7830, in SetQualifier
    **extra)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_operations.py", line 880, in _imethodcall
    for x in params.items() if x[1] is not None]
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_obj.py", line 4060, in tocimxml
    return value.tocimxml()
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_obj.py", line 3969, in tocimxml
    translatable=self.translatable)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_xml.py", line 346, in __init__
    xval = VALUE_ARRAY(value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_xml.py", line 419, in __init__
    self.appendChildren(values)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_xml.py", line 197, in appendChildren
    self.appendChild(child)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 113, in appendChild
    if node.nodeType == self.DOCUMENT_FRAGMENT_NODE:
AttributeError: 'unicode' object has no attribute 'nodeType'

The problem is the array=True which conflicts with the value.  The constructor does not compare the
types and error return but depends on cimxml which generates an error when constructing the xml.

**Comment by KSchopmeyer** [comment]
We agree that this one probably needs some kind of consistency checking.

**Comment by KSchopmeyer** [comment]
Add a consistency test
