### ISSUE TITLE
recorder fails in testclient test ValidResponse5.yaml

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#663]
I added code to use the recorder output on all tests in testclient.  It fails on the testValidResponse5.yaml
with the following error:

Traceback (most recent call last):
  File "testsuite/test_client.py", line 503, in test_all
    self.runyamlfile(relfn)
  File "testsuite/test_client.py", line 514, in runyamlfile
    self.runtestcase(testcase)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/httpretty/core.py", line 1146, in wrapper
    return test(*args, **kw)
  File "testsuite/test_client.py", line 691, in runtestcase
    (tc_name, op_name, raised_traceback_str))
AssertionError: Testcase ValidResponse5: No exception was expected to be raised by PyWBEM operation GetInstance, but an exception was actually raised:
Traceback (most recent call last):
  File "testsuite/test_client.py", line 621, in runtestcase
    result = op_call(**op_args)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/cim_operations.py", line 5835, in GetInstance
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/_recorder.py", line 335, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/pywbem-0.11.0.dev0-py2.7.egg/pywbem/_recorder.py", line 500, in record
    self._fp.write(data)

UnicodeEncodeError: 'ascii' codec can't encode character u'\ud7ff' in position 1059: ordinal not in range(128)

The error is legitimate in that it is the illegal unicode test... Have not looked further to see if there is other issue but this does stop the test whereas without recorder, the test cases continue.  

NOTE: I created the test by simply turning on the recorder in test client with output to dev/dull

**Comment by andy-maier** [comment]
Fixed by PR #696.
