### ISSUE TITLE
Recorder issues

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#676]
Several issues with the recorder as follows:

1. indent output yaml by 4 to be more consistent with normal use. Include issue # 609 in this, set indent to 4 (currently 2)
2. Issue where open/pull does not correctly return context info.
It returns:
```
pullresult:
        - true
        - null
```
Where is should be in the form

```
        pullresult:
            context:
                - blahblah
                - root/cimv2
            eos: false
```

3. (New problem) Recorder does not write utf-8 in python 2.7.  Fixed for now by modifying the open in both run_cim_operations.py and test_recorder.py to use codecs.open(...) with python 2.

4.  (New problem)  Issue with recorder writing and then testing some datetime properties.  Results cannot be compared. Produces an exception stating that naive and timezone aware cannot be compared. Working solution in test_recorder.py is to insure that all datetimes are timezone aware.  See issue #698

5. Exception from run_cimoperations.py, Representer cannot handle datetime.
Actually, the representer cannot handle the python timedelta type.  Datetime appears to pass through
correctly.  The solutions are a) find some way to bypass that particular type, or b) extend the representer to handle timedelta correctly NOTE: This issue moved to issue#702

```
======================================================================
ERROR: test_non_empty_arrays (__main__.InvokeMethod)
Call with non-empty arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testsuite/run_cim_operations.py", line 2359, in test_non_empty_arrays
    RefArray=[name, name])
  File "testsuite/run_cim_operations.py", line 169, in cimcall
    result = fn(*pargs, **kwargs)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/cim_operations.py", line 6961, in InvokeMethod
    self.operation_recorder.record_staged()
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 352, in record_staged
    self.record(pwargs, pwresult, httpreq, httpresp)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 514, in record
    default_flow_style=False)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 84, in <lambda>
    _represent_ordereddict(dumper, u'tag:yaml.org,2002:map', value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 65, in _represent_ordereddict
    node_value = dump.represent_data(item_value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 84, in <lambda>
    _represent_ordereddict(dumper, u'tag:yaml.org,2002:map', value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 65, in _represent_ordereddict
    node_value = dump.represent_data(item_value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 84, in <lambda>
    _represent_ordereddict(dumper, u'tag:yaml.org,2002:map', value))
  File "/home/kschopmeyer/pywbem/githubpywbem/pywbem/pywbem/_recorder.py", line 65, in _represent_ordereddict
    node_value = dump.represent_data(item_value)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 215, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 101, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/kschopmeyer/.virtualenvs/pywbem27/local/lib/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: 00000000000000.000000:000
```

**Comment by andy-maier** [comment]
Addressed in PR #696.
