### ISSUE TITLE
Type error in run_cimoperations test with python3

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbem#718]
Issue with bytes vs.  unicode python 3.  This may be just a test issue but the folowing test runs in python 2 but not python 3
  
The varaible for namespace, etc. is

TEST_PEG_STRESS_NAMESPACE = "test/TestProvider"
TEST_PEG_STRESS_CLASSNAME = "TST_ResponseStressTestCxx"
======================================================================
ERROR: test_propertylist2 (__main__.IterEnumerateInstances)
Test withone item property list.

The
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testsuite/run_cim_operations.py", line 4623, in test_propertylist2
    MaxObjectCount=100, PropertyList=property_list)
  File "testsuite/run_cim_operations.py", line 4444, in run_enum_test
    for inst in generator:
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.11.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 2054, in IterEnumerateInstances
    MaxObjectCount=MaxObjectCount, **extra)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.11.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 4165, in OpenEnumerateInstances
    namespace = self._iparam_namespace_from_namespace(namespace)
  File "/home/kschopmeyer/.virtualenvs/pywbem3/lib/python3.4/site-packages/pywbem-0.11.0.dev0-py3.4.egg/pywbem/cim_operations.py", line 1392, in _iparam_namespace_from_namespace
    'string, got: %s' % type(obj))
TypeError: Expecting None (for default), or a namespace string, got: <class 'bytes'>

**Comment by andy-maier** [comment]
Fixed in PR #721.
