### ISSUE TITLE
DistutilsSetupError complaining about setuptools to old in make develop on standard RHEL 7.3

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#760]
Output of `make develop` on RHEL 7.3 with standard versions of Python packages (i.e. just the latest OS-level Python packages):

```
python setup.py develop_os
Traceback (most recent call last):
  File "setup.py", line 551, in <module>
    sys.exit(main())
  File "setup.py", line 294, in main
    import_setuptools()
  File "/home/maiera/Projects/pywbem/repos/pywbem/os_setup.py", line 1653, in import_setuptools
    (min_version, min_version)
distutils.errors.DistutilsSetupError: The required version of setuptools (>=12.0) is not installed and can't be
installed while this script is running. Please install the required version
first, using:

    pip install --upgrade 'setuptools>=12.0'

make: *** [develop] Error 1
```

Fix is to ensure in the makefile that a number of core packages are updated first (pip, setuptools, wheel).

**Comment by andy-maier** [comment]
Fixed in PR #764 by upgrading setuptools before these steps actually execute.
