### ISSUE TITLE
six 1.11.0 causes TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbem#765]
Version 1.11.0 of the six package was released yesterday and causes:

```
$ PYTHONPATH=. python -c "import pywbem"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pywbem/__init__.py", line 48, in <module>
    from ._logging import *  # noqa: F403,F401
  File "pywbem/_logging.py", line 138, in <module>
    class PywbemLoggers(six.with_metaclass(MetaPywbemLoggers)):
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

This issue has been encountered by several more folks and has been reported as issue benjaminp/six#210.

This issue is to track its resolution, or to make whatever change in pywbem could fix this.

**Comment by andy-maier** [comment]
Addressed by PR #766.
